### ISSUE TITLE
Profiling suite

### ISSUE THREAD

**Issue by albanie** [beartype/beartype#2] opened 2020-04-06 04:12 UTC
I think it would be useful to include a basic profiling suite so that users have a measure of the kinds of overhead they should expect for a given scenario.  I can likely add this part.  This information does not appear to be readily available for other tools (e.g. [typeguard](https://github.com/agronholm/typeguard/issues/117#event-3156010658)).

**Comment by leycec** [comment] 2020-04-07 05:24
That's... a *really* sound idea. While developing [BETSE\[E\]](https://gitlab.com/betse/betse), I vaguely recall us utilizing some variant of:

* The [stdlib `cProfile` module](https://docs.python.org/3/library/profile.html) for profiling time consumption.
* The [third-party `pympler` package](https://pythonhosted.org/Pympler) for profiling space consumption.

Since we ain't slinging around `n`-dimensional Numpy arrays here, space probably isn't the concern; it's time. Thankfully, I can't recall any specific complaints with `cProfile`. Perhaps wrapping that with a higher-level API exhibiting timings for common scenarios makes common sense, as you suggest?

Likewise, I've also considered integrating profiling into our eventual Travis CI-driven `py.test` suite to prevent performance regressions. Although I (of course) have no idea how to specifically go about that, how agonizing could it possibly be? <sup>*spastic eye twitch*</sup>

For maintainability, I'd ideally like to unify the two. Assuming this is feasible, the same timings privately performed under CI should also be the same timings publicly exposed by this hypothetical profiling suite to end users. Maybe? If you have profound experience with this sort of thing, please teach us that we also may know profiling satori.

**Comment by albanie** [comment] 2020-04-09 09:04
That sounds like a sensible way to go. `cProfile` has done a reasonable job for me in the past.
I'll formulate a list of "typical" scenarios that we could reasonably expect to be beartyped.  We can perhaps integrate an auto-generated table into the README that contrasts beartyping with a few other reference approaches to calibrate their expectations (e.g. how does it compare to hardcoded `isinstance()` statements/other runtime checking libraries) etc.

Caveat: my timing experience is not profound.

**Comment by leycec** [comment] 2020-04-25 04:29
Un:bear:ably fast runtime type checking in pure Python.

**Comment by leycec** [comment] 2020-04-25 04:32
**lol.** Accidentally closed due to negligence, so we reopen. In *other* news, our first stable release (i.e., `beartype 0.1.0`) is about to mic drop. Let's see what the caffeine-fueled weekend brings.

**Comment by leycec** [comment] 2020-09-03 05:58
To [narcissistically quote myself](https://github.com/beartype/beartype/issues/3#issuecomment-686266552), because that's just how narcissists roll:

> Another thing you'll possibly love is that `beartype` now provides an [out-of-the-box profiling suite quantitatively timing itself against competing implementations](https://github.com/beartype/beartype#id4) – which currently just means [typeguard](https://github.com/agronholm/typeguard), because [enforce](https://github.com/RussBaz/enforce) died a few years ago and [pytypes](https://github.com/Stewori/pytypes) followed it last year. Which sucks, because now Python's runtime type-checking ecosystem has lost most of its biodiversity and is basically shambling shambolically on its last gangrenous legs. On the bright side, `beartype` is stupidly fast. Which rocks, because that was the entire point of the last three months of my life. <sup>...*precious summer, come back to me!*</sup>

Timings or it didn't happen, so:

```
beartype profiler [version]: 0.0.1

python    [version]: Python 3.7.8
beartype  [version]: 0.2.1
typeguard [version]: 2.9.1

========================== str (100 calls each loop) ==========================
decoration         [none     ]: 100 loops, best of 3: 380 nsec per loop
decoration         [beartype ]: 100 loops, best of 3: 344 usec per loop
decoration         [typeguard]: 100 loops, best of 3: 13.4 usec per loop
decoration + calls [none     ]: 100 loops, best of 3: 15.5 usec per loop
decoration + calls [beartype ]: 100 loops, best of 3: 486 usec per loop
decoration + calls [typeguard]: 100 loops, best of 3: 6.93 msec per loop

==================== Union[int, str] (100 calls each loop) ====================
decoration         [none     ]: 100 loops, best of 3: 2.93 usec per loop
decoration         [beartype ]: 100 loops, best of 3: 359 usec per loop
decoration         [typeguard]: 100 loops, best of 3: 16.6 usec per loop
decoration + calls [none     ]: 100 loops, best of 3: 18.3 usec per loop
decoration + calls [beartype ]: 100 loops, best of 3: 540 usec per loop
decoration + calls [typeguard]: 100 loops, best of 3: 11.3 msec per loop

=============== List[object] of 150 items (839 calls each loop) ===============
decoration         [none     ]: 100 loops, best of 1: 3.65 usec per loop
decoration         [beartype ]: 100 loops, best of 1: 343 usec per loop
decoration         [typeguard]: 100 loops, best of 1: 19 usec per loop
decoration + calls [none     ]: 100 loops, best of 1: 143 usec per loop
decoration + calls [beartype ]: 100 loops, best of 1: 1.43 msec per loop
decoration + calls [typeguard]: 100 loops, best of 1: 2.14 sec per loop
```

Note the last two lines in particular:

```
decoration + calls [beartype ]: 100 loops, best of 1: 1.43 msec per loop
decoration + calls [typeguard]: 100 loops, best of 1: 2.14 sec per loop
```

*Yeah.* There's a bit of a performance gap there.

And with that closing bravado, we now explode our heads as one and (more importantly) close this long-standing issue. **Boom!** :exploding_head:

**Closed by leycec** 2020-09-03 05:58 UTC
