### ISSUE TITLE
[Feature Request] Readable type-checking violation messages, please Gods.

### ISSUE THREAD

**Issue by felixchenier** [beartype/beartype#216] opened 2023-03-09 21:58 UTC
In reference to our discussion here: https://github.com/beartype/beartype/issues/174#issuecomment-1260499009

I want to use BearType for an API dedicated to non-technical people, and the current roar from BearType is currently scary and wordy:

```
BeartypeCallHintParamViolation: @beartyped __main__.function2() parameter b='a' violates type hint <class 'int'>, as str 'a' not instance of int.
```

This would be more digestible for new/light-programmer:

```
BeartypeCallHintParamViolation: Function __main__.function2() expected parameter b to be of type int, but a value of type str was provided instead: 'a'.
```

Since a good string for one is a bad string for another, it would be **super** cool to be able to provide custom strings with placeholders via the BearType's configuration option, for instance:

```python
param_error_message = "Function {function_name} expected parameter {param_name} to be of type {expected_type}, but a value of type {received_type} was provided instead: {param_value}."
```

Isn't it sexy?

OK I know it messes with the color option, it's not that simple, and I looked at the code that generates those strings and I won't dive into that, but I still think that the idea is cool :-)

For me it would make a real difference.

**Comment by felixchenier** [comment] 2023-03-09 22:58
Just testing at what point I could stretch my luck.

Talking of customizing error messages, it would be still greater if we can also provide an alternate exception, e.g.:

```python
param_error_exception = TypeError
```

such that type errors would result in:

```
TypeError: Function __main__.function2() expected parameter b to be of type int, but a value of type str was provided instead: 'a'.
```
instead of 

```
BeartypeCallHintParamViolation: Function __main__.function2() expected parameter b to be of type int, but a value of type str was provided instead: 'a'.
```

Why? While it's probably best for a full Python program to use beartype's exception, for an API I like to put one layer of abstraction between my API interface, and beartype that is my API implementation. My API users don't know about beartype, what they did when they make an error really is a TypeError, and I think this is what they should get.

Maybe I'm just asking too much, but still, you get the idea!

**Comment by patrick-kidger** [comment] 2023-03-10 05:47
Custom error messages would be awesome for use in jaxtyping as well, c.f. https://github.com/google/jaxtyping/issues/6.

The issue is that an `__instancecheck__` against one of jaxtyping's custom types can only return a `True`/`False`, but nothing more. This means getting error messages like
```
beartype.roar.BeartypeCallHintParamViolation: @beartyped __main__.f() parameter x="Array(1, dtype=int32, weak_type=True)" violates type hint <class 'jaxtyping.Float[Array, 'dim1']'>, as <protocol "jaxlib.xla_extension.ArrayImpl"> "Array(1, dtype=int32, weak_type=True)" not instance of <class "jaxtyping.Float[Array, 'dim1']">.
```
which is a rather terrifying error message to get in place of "you annotated for arrays of shape `(dim1,)`, but passed in an array of shape `()`, you dummy".

I'm perhaps imagining a `__beartype_isinstance__` method, which returns a `tuple[bool, None | str]`: did it pass, and if not, why not?

(For reproducability: the above error message was generated using this script:
```python
from beartype import beartype
from jaxtyping import Array, Float
import jax.numpy as jnp

@beartype
def f(x: Float[Array, "dim1"]):
    pass

f(jnp.array(1))
```
)

**Comment by leycec** [comment] 2023-03-10 08:41
**OMG.** You guys are *amazing*! Although superficially similar, I actually see three distinct feature requests here. Let us tease out the signal from the noise. In descending chronological order, these are...

## User-configurable Violation Messages

In this feature request, we add a new `BeartypeConf(violation_template: str, ...)` parameter enabling users to customize `BeartypeCallHintViolation` exception messages.

It is, indeed, sexy. It's also probably *extremely* non-trivial. Your gut intuition to abandon ship was the correct decision, @felixchenier:

> I looked at the code that generates those strings and I won't dive into that

:rofl: 

Honestly, the more prudent decision might just be to **abandon our current violation output in favour of your more human-readable alternative.** Notably...

```python
# Instead of this...
BeartypeCallHintParamViolation: @beartyped __main__.function2()
parameter b='a' violates type hint <class 'int'>, as str 'a' not
instance of int.

# ...you want this.
BeartypeCallHintParamViolation: Function __main__.function2() expected
parameter b to be of type int, but a value of type str was provided
instead: 'a'.
```

I firmly agree with *almost* all of your proposed improvements, Felix. I'm strongly considering just revising our current violation output in favour of your preferred template. Specifically:

* `"Function"` reads much better than `@beartyped`. I mean, `@beartyped`? Really? That's not even a real thing! There *is* no `@beartype.beartyped` decorator. I wholly agree with this. My younger self has much to answer for. :face_with_head_bandage: 
* You drop the noun `"hint"` entirely. Yet again, this makes total sense. End users don't need to know that type hints are even involved. Too much information only obstructs the truth. I give thumbs that are up. :+1: 
* You drop the equal sign between the parameter name and value. Again, you're right to do so. The Python language itself favours human-readable nouns and verbs (like `"parameter {name} to be of type {type}"`) rather than syntactic sugar (like `"parameter {name}={value} violates type hint {type}"`). Readability was Guido's ingenious 4D chess move. Preserving that in our exception messages is the only Pythonic approach. Thumbs are still up. :+1: 
* You reverse the order of clauses. Rather than describe what the user did wrong first, you instead describe what the API expected first. Yet again, this is the right approach.
* Now that you mention it, I *think* I'd prefer the active voice to the passive voice here. That is, rather than the substring `"but a value of type str was provided instead:"` in the passive voice, I'd prefer a substring `"but received a value of type str instead:"` in the active voice. Does that sound right to you?
* You delay displaying the erroneous value that the user passed until the very end. In theory, I strongly agree with this yet again. In practice, this might be a bit non-trivial to accomplish. Consider unions, for example:

```python
from beartype import beartype

@beartype
def yam(ok: int | list[str]): pass
yam([b'ugh'])
```

The above prints:

```python
BeartypeCallHintParamViolation: @beartyped __main__.yam()
parameter ok=[b'ugh'] violates type hint int | list[str],
as list [b'ugh']:
* Not int.
* list index 0 item bytes b'ugh' not instance of str.
```

Delaying displaying the erroneous list `[b'ugh']` until the very end of that output is pretty much a non-starter, right? Still, everything *else* discussed above still applies. Incorporating all of your other suggestions yields output resembling:

```python
BeartypeCallHintParamViolation: Function __main__.yam()
expected parameter ok to be of type int | list[str],
but received value of type list[bytes] instead: [b'ugh']

Specifically, [b'ugh']:
* Not int.
* List index 0 item b'ugh' not str.
```

In the above approach, we now append your templatized approach with an optional analysis of what exactly went wrong for a subset of type hints like unions that support that.

The only practical issue that remains is: **we'll need to start constructing the expected type hint** (e.g., `list[bytes]`) in the above output. Fascinatingly, this is *exactly* what @wesselb is doing in Plum's `type_of()` function (if I recall correctly). Looks like we'll need to borrow that into the @beartype codebase at some point! At least it's all been done for us. Smiley cat gives thanks. :smile_cat: 

## User-configurable Violation Types

In this feature request, we add a new `BeartypeConf(violation_type: type[Exception], ...)` parameter enabling users to customize the type of exception raised. You would then configure your own `@beartype` decorator like so, @felixchenier:

```python
from beartype import beartype, BeartypeConf

# @beartype decorating raising "TypeError" rather than
# "BeartypeCallHintViolation" exceptions.
beartypeerror = beartype(conf=BeartypeConf(violation_type=TypeError))
```

**This is trivial.** Rejoice, everyone! This is the low-hanging fruit that we will pluck when we find a spare clone lazing around to do this for us. Get back to work, clone!

## Class-specific Exception Messages

**Ah-ha!** Plugin system ahoy, @patrick-kidger. Yes, you're absolutely right. That exception message is appallingly non-human-readable. I would punch the nearest pliable object repeatedly if I ever got an exception message like that. 

This is actually a desperate plea for **[Feature Request] Plugin API, Phase V: The `__beartype_isinstance__()` protocol** in disguise. See also feature requests #191, #192, and #193. Of course, none of those do what you need. But they *do* demonstrate that a sprawling and poorly documented plugin system is a thing we should promise to do sometime.

I see two alternate APIs here:

* We run with the proposed `def __beartype_isinstance__(self, obj: object) -> tuple[bool, None | str]: ...` protocol. This works, but has a bit of a drawback: you're *probably* violating DRY by duplicating validation logic between this new `__beartype_isinstance__()` and the existing `__instancecheck__()` in the metaclass. Maybe? Though, I suppose that one could always just internally defer to the other *or* just drop `__instancecheck__()` entirely (in which case `jaxtyping` would strictly require users to use `@beartype` everywhere, which is just great from my biased perspective but not so great from everybody else's more honest perspective). Still, it seems a little excessive. I wonder if instead...
* We pare that down to an alternate `def __beartype_violation_message__(self, obj: object) -> None | str: ...` protocol, which returns either:
  * If the passed object `obj` satisfies the current type hint `self`, `None`.
  * Else, a human-readable substring detailing exactly how `obj` violates `self`.

In the latter case, you'd still define an `__instancecheck__()` in the metaclass; @beartype would then still defer to a standard `isinstance(obj, hint)` check like it currently does. If that check returns `False`, @beartype would then call your hint-specific `__beartype_violation_message__()` dunder method (if defined) to embed a hint-specific description in its violation message.

Since @beartype will embed that substring in its own larger exception message, there will *probably* need to be a few ground rules governing how exactly that message is formatted (e.g., as a lowercase sentence fragment with no prefixing or trailing punctuation). Blagh! Let's not even begin to consider l18n and i18n concerns here, because my feeble brain is already imploding.

:expressionless: :exploding_head: :boom:

**Comment by patrick-kidger** [comment] 2023-03-10 14:54
Right! So I actually deliberately tied the check and the message together, so that the expensive checking logic only has to be the run once.

That said, if we're raising a beartype error then we're probably not coming back from that, so the additional runtime cost probably isn't a big deal.

**Comment by felixchenier** [comment] 2023-03-10 16:07
@leycec 

> Now that you mention it, I think I'd prefer the active voice to the passive voice here. That is, rather than the substring "but a value of type str was provided instead:" in the passive voice, I'd prefer a substring "but received a value of type str instead:" in the active voice. Does that sound right to you?

Yes, it's way better in the active voice.

> You delay displaying the erroneous value that the user passed until the very end. In theory, I strongly agree with this yet again. In practice, this might be a bit non-trivial to accomplish. Consider unions, for example:
```
from beartype import beartype

@beartype
def yam(ok: int | list[str]): pass
yam([b'ugh'])
```
> The above prints:
```
BeartypeCallHintParamViolation: @beartyped __main__.yam()
parameter ok=[b'ugh'] violates type hint int | list[str],
as list [b'ugh']:
* Not int.
* list index 0 item bytes b'ugh' not instance of str.
```
> Delaying displaying the erroneous list [b'ugh'] until the very end of that output is pretty much a non-starter, right?

I'd say it's a matter of taste. In my option, this pretty output, starting from "as list [b'ugh']:" is superfluous anyway, as it doesn't add really new information. If we know that [b'ugh'] violates int | list[str], then it's obvious that it's neither an int, neither a list[str]. At this point, the user has well enough clues to figure out why its value was rejected. I understand that you want to guide the user up to the inners of the list, to know which element was wrong, but is it really worth it? In any case, your suggestion is also good, clear enough, and helps more than scares.

---

For the user-configurable violation types, just after sending it I realized that in reality, all I probably have to do is to monkey-patch beartype exceptions, something like: `beartype.exceptions.BeartypeCallHintParamViolation = TypeError`, whereever you really defined those exception classes. Maybe it's not that simple though. Anyway.

**Comment by leycec** [comment] 2023-03-11 07:53
@patrick-kidger: **Ah-ha!** Yes, indeed. This is all true, because you are sagely:

> Right! So I actually deliberately tied the check and the message together, so that the expensive checking logic only has to be the run once.
>
> That said, if we're raising a beartype error then we're probably not coming back from that, so the additional runtime cost probably isn't a big deal.

Absolutely. Efficiency is *definitely* no longer a concern here. But... I now see exactly what you're intelligently saying. To produce the message, you have to perform the check. So you'd might as well just return both. Right?

Of course, a message of `None` implies a check value of `False`; likewise, a non-`None` message  implies a check value of `True`. So, returning a boolean is *probably* superfluous. I think? If so, we could slightly improve the space and time efficiency of `__beartype_isinstance__()` or `__beartype_violation_message__()` or *whatevahs* by just returning the message. I think?

I'm seeing a lot of "I think?" above, which means I'm probably on shaky ground here. `</gulp>`

**Comment by leycec** [comment] 2023-03-11 08:11
@felixchenier: You always bring those hard-hitting questions! Like this...

> I understand that you want to guide the user up to the inners of the list, to know which element was wrong, but is it really worth it?

:sob: 

It's all true. I just spent *forever* writing that string formatting code years ago and am now looking for some nebulous reason to preserve it – regardless of whether I should. Sanity be damned! This makes me the most recent victim of the Sunk Cost Fallacy.

Oh. Right. There *is* a useful reason to preserve this output. It's true that, in this specific case, the additional explanation doesn't actually yield any useful discussion. The function expected `list[str]`. It got `list[bytes]`. Done! That's all we needed to say.

But I'm certain there are non-trivial use cases where the additional explanation is pretty much mandatory. The `__beartype_violation_message__()` API or *whatevah* that @patrick-kidger and I are mercilessly debating is a good example. In that case, the type hint alone doesn't convey enough metadata to describe why the type check failed, because most of the actual type check is happening in a hidden `__beartype_violation_message__()` method somewhere; users really *would* need the full explanation there.

</hr>

And this...

```python
beartype.roar.BeartypeCallHintParamViolation = TypeError
beartype.roar.BeartypeCallHintReturnViolation = TypeError
```

**OH, GODS.** If your package is the only package in your stack that's using @beartype **and if you can guarantee that will always be the case,** then monkey-patching @beartype is *sorta* fine. But if any of those constraints fail to hold, then you're probably breaking things without knowing that you're breaking things.

After all, the whole point of differentiating @beartype exceptions from builtin exceptions is so that everybody can catch @beartype exceptions without also catching builtin exceptions. Right? For example:

```python
try:
    some_beartyped_func()
except beartype.roar.BeartypeCallHintParamViolation:
    do something smart here
except TypeError:
    do something else entirely here
```

If you globally smash `beartype.roar.BeartypeCallHintParamViolation` and replace it with `TypeError` behind everybody's backs, then the above code no longer behaves as expected. I am crying while trying to smile. :smiling_face_with_tear:

This is why we should add a new `violation_type` parameter to `BeartypeConf`. You need this, so other devs probably need this too. Let's do this right. The alternative is Microsoft themselves burning down this issue tracker in a fit of inchoate (but justified) rage. Don't let Microsoft do that, Félix!

**Comment by patrick-kidger** [comment] 2023-03-11 16:08
Yup! Returning just a `None | str` looks good to me.

**Comment by felixchenier** [comment] 2023-03-12 17:03
> If you globally smash beartype.roar.BeartypeCallHintParamViolation and replace it with TypeError behind everybody's backs, then the above code no longer behaves as expected. I am crying while trying to smile. 🥲

Sorry about it, this is what you get when you allow scientists to play with serious tools! You're right, this is the hacky way and it's not a good way. Anyway, I'm done with my suggestions on this feature request. Your proposition of new error string, along with the proposition to allow alternate styles, are completely fulfilling my initial request.

**Comment by leycec** [comment] 2023-04-20 06:55
**Awwwwww.** You so nice, Felix. And... I not so nice. It's taken me simply *forever* to properly respond to this incredible feature request. I blame video games.

First, Let's gently pry this apart into smaller and more bite-sized issues: :scissors: 

* Issue #234 now tracks @felixchenier's excellent request for **User-configurable type-checking violation types** (e.g., `TypeError` rather than `BeartypeCallHintViolation`).
* Issue #235 now tracks @patrick-kidger's excellent request for **Class-specific type-checking violation messages** (e.g., `"Your JAX tensor sucks, bro."` rather than `"<protocol "jaxlib.xla_extension.ArrayImpl">
"Array(1, dtype=int32, weak_type=True)" not instance of <class
"jaxtyping.Float[Array, 'dim1']">."`).

Second, I've begun to quietly resolve @felixchenier's original request for improved exception messages. Behind the scenes, magic is happening. Shh! Don't tell anybody or they might ask us to do other stuff. :shushing_face:

Notably, @beartype now prefixes type-checking violation messages with a short description of the responsible callable (e.g., `"Function"`, `"Coroutine factory method"`) rather than the meaningless prefix `"@beartyped"` like we used to: e.g.,

```python
from beartype import beartype

@beartype
class CheapMeat(object):
    def the_dogs_eat(self) -> int:
        return 'Feed doggo meat. Doggo is now happy.'

CheapMeat().the_dogs_eat()
```

The above now raises the *slightly* more readable message:

```
beartype.roar.BeartypeCallHintReturnViolation: Method
__main__.CheapMeat.the_dogs_eat() return 'Feed doggo meat.
Doggo is now happy.' violates type hint <class 'int'>, as
str 'Feed doggo meat. Doggo is now happy.' not instance of int.
```

Note the prominent prefix `"Method"` rather than `"@beartype"`. This will be included in `beartype 0.13.2` hopefully released tomorrow. It's not much. It's better than nothing. Maybe?

Let's see if we can get all of the way there for `beartype 0.14.0`! I believe in miracles.

**Comment by leycec** [comment] 2024-01-06 05:37
**Resolved by e789ba72ab.** Thanks so much for your extreme patience, @felixchenier! 2024 snuck up on us like a cat in the grass you don't see until the last minute, didn't it? But all's well that ends well. I bring good news from the soggy bogs of Ontario.

I'm on the cusp of publicly releasing your great work with @beartype 0.17.0 in a few days. Until then, have an awesome weekend. With any luck, we'll all be shovelling snow and skiing all over the place next week. :snowman_with_snow: :skier:

**Closed by leycec** 2024-01-06 05:37 UTC

**Comment by felixchenier** [comment] 2024-01-06 14:07
Hi @leycec 
A very nice 2024 year to you, with maybe a little bit of snow?
Hey just before doing this release, did you have time to check my comment on #311? It proposes a tiny little extension to HintOverrides which renders the "ArrayLike" hack useless, and I'm sure it may have many other still unknown advantages. If you agree with this suggestion, we should do it before releasing 0.17.0 because it's not compatible with the current HintOverrides value (change from a type to a tuple[str, type]).

**Comment by leycec** [comment] 2024-01-09 03:21
> with maybe a little bit of snow?

...we got *nuthin',* man! A whole boatload of nuthin'. What is this, Jamaica? Because this feels like Jamaica.

> Hey just before doing this release, did you have time to check my comment on #311?

**Gah!** So sorry about that. Your awesome response somehow dropped right off my radar. Clearly, I need a new radar. The one in our basement appears to be broken. :sob: 

I totally see where you're coming from there. Thankfully, Python ≥ 3.12 **+** @beartype 0.17.0 *does* actually provide a standardized solution for what you want to do: [PEP 695-compliant `type` aliases](https://docs.python.org/3/library/typing.html#type-aliases). `type` aliases have a simple name (which @beartype will present to users in exception messages) but evaluate to an arbitrarily complex type hint (which @beartype will use behind-the-scenes to perform actual type-checking).

To quote [the official article on `type` aliases](https://docs.python.org/3/library/typing.html#type-aliases):

> Type aliases are useful for **simplifying complex type signatures.** For example:

```python
from collections.abc import Sequence

type ConnectionOptions = dict[str, str]
type Address = tuple[str, int]
type Server = tuple[Address, ConnectionOptions]

def broadcast_message(message: str, servers: Sequence[Server]) -> None:
    ...

# The static type checker will treat the previous type signature as
# being exactly equivalent to this one.
def broadcast_message(
        message: str,
        servers: Sequence[tuple[tuple[str, int], dict[str, str]]]) -> None:
    ...
```

For your use case of the complex `numpy.typing.ArrayLike` union, you could simply define a `type` alias whose name is `ArrayLike` and whose value is `numpy.typing.ArrayLike`. In fact, NumPy itself should do just that to simplify everyone's lives already. Right? Release the code hounds, Watson! :poodle: 

```python
from numpy.typing import ArrayLike as np_ArrayLike

# Simply type alias of a complex type hint: arise, you fiend! Arise to glory!
type ArrayLike = np_ArrayLike
```

## What's the Catch, Bub?

Two catches:

* **This requires Python ≥ 3.12.** When I say "This requires Python ≥ 3.12," I mean *really* requires. If you even try to define a `type` alias in Python < 3.12, you'll get a non-human-readable `SyntaxError` – even if you try to hide that `type` alias from older Python versions with `if` conditionals like `if version_info < (3, 12):`. Hiding doesn't work. You either need to:
  * Isolate all `type` aliases to a unique submodule imported *only* under Python ≥ 3.12.
  * Dynamically declare `type` aliases with the `exec()` builtin. This is the lazy way. Thus, this is what we do below.
* **This requires @beartype ≥ 0.17.0,** which has yet to be officially released. <sup>*...heh.*</sup>

You are now thinking: "`type` aliases seriously suck, dude. Seriously." Fear not, @leycec is here. Allow me to now dispel all your fears with insane code that should make you cringe. I say, "Embrace that cringe."

Let's *gooooooooooooo*:

```python
from numpy.typing import ArrayLike as np_ArrayLike
from sys import version_info
from typing import TYPE_CHECKING

# If we're being statically type-checked, just declare a type alias directly.
if TYPE_CHECKING:
    type ArrayLike = np_ArrayLike
# If the current Python interpreter ≥ 3.12, dynamically declare a type alias to
# avoid "SyntaxError" complaints from older Python interpreters.
elif version_info >= (3, 12):
    exec('type ArrayLike = np_ArrayLike')  # <-- don't ask. don't tell.
# Else, the current Python interpreter sucks. In this case, define a stupid
# obsolete old-school type alias with deprecated "typing" attributes. Just. Do. It.
else:
    from typing import TypeAlias  # <-- deprecated, but who cares
    ArrayLike: TypeAlias = np_ArrayLike
```

*...heh.* What could be simpler, huh? :face_with_spiral_eyes:

**Comment by felixchenier** [comment] 2024-01-09 14:42
@leycec That's cute little awful code, thanks!

OK I understand the type aliases in Python 3.12, thanks for learning it to me. I just tried it and it's magical. It completely solves my comment in #311 so there is no need to implement it again. For some reason, while time passes and until it's acceptable to require Python>=3.12, I still prefer my use of NewType in #311.

So that's fine, you won't find my body lying on the road to 0.17.0 urging you to block the release or die. I'll smartly yell elsewhere instead.

Thanks again for your work, I'm eager to switch my code to beartype :-D

**Comment by leycec** [comment] 2024-01-10 05:22
Oh, you're most welcome. Thanks so much for your kind and hilarious comments. Also, you're not wrong:

> ...I still prefer my use of NewType in #311.

*...yeah.* They botched the implementation of `type` aliases. It's a shame they can't be used in open-source or even most commercial offerings. Ain't nobody gonna require Python ≥ 3.12 anytime soon. That said, `NewType` *does* still have the disadvantage of angering mypy and `pyright`. I think?

**Behold!** Code that pacifies mypy and `pyright`:

```python
from numpy.typing import ArrayLike as np_ArrayLike
from typing import TYPE_CHECKING, NewType, TypeAlias

# If we're being statically type-checked, declare an obsolete type alias that pacifies mypy.
if TYPE_CHECKING:
    ArrayLike: TypeAlias = np_ArrayLike
# Else, we are normal Python. In this case, define a clever type alias that angers mypy.
else:
    ArrayLike = NewType('ArrayLike', np_ArrayLike)
```

But when you've gone that far, it's only one small step further to full madness:

```python
from numpy.typing import ArrayLike as np_ArrayLike
from sys import version_info
from typing import TYPE_CHECKING, NewType, TypeAlias

# If we're being statically type-checked, declare an obsolete type alias that pacifies mypy.
if TYPE_CHECKING:
    ArrayLike: TypeAlias = np_ArrayLike
# Else, we are normal Python. If we are Python ≥ 3.12, dynamically declare a type alias to
# avoid "SyntaxError" complaints from older Python interpreters.
elif version_info >= (3, 12):
    exec('type ArrayLike = np_ArrayLike')  # <-- don't ask. don't tell.
# Else, we are obsolete Python. In this case, define a clever type alias that angers mypy.
else:
    ArrayLike = NewType('ArrayLike', np_ArrayLike)
```

I'll stop now. :rofl:
