### ISSUE TITLE
cannot import typing from beartype

### ISSUE THREAD

**Issue by matanster** [beartype/beartype#95] opened 2022-02-05 21:36 UTC
I pip installed beartype and therefore have version 0.9.1 installed. However, I seem to fail using the following import statement which is mentioned [in the docs](https://github.com/beartype/beartype#are-we-on-the-worst-timeline):

```
from beartype import typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'typing' from 'beartype' (~/anaconda3/envs/video-capture/lib/python3.8/site-packages/beartype/__init__.py)
```

What might I be missing?
Thank you for you help and for this package.

I'd really like to use this typing in order to become future proof from python's typing package breaking changes.

**Comment by leycec** [comment] 2022-02-05 23:50
You're not missing, actually! This is entirely on us – because I sadly have yet to release `beartype 0.10.0`, which introduces the `beartype.typing` submodule. Until then, [please see this similar answer for a temporary alternative resolution](https://github.com/beartype/beartype/issues/93#issuecomment-1025425025).

And thanks so much for the generous interest, @matanster. :smile:

**Comment by leycec** [comment] 2022-02-05 23:50
*marked as duplicate of #81*

**Closed by leycec** 2022-02-05 23:50 UTC
