### ISSUE TITLE
python 3.8 raises warning in from beartype import beartype

### ISSUE THREAD

**Issue by djhenderson** [beartype/beartype#30] opened 2021-03-05 20:17 UTC
Python 3.8 on Win10 raises warnings when using `PYTHONDEVMODE=1`:

```
C:\Program Files\Python39\lib\site-packages\beartype\_util\hint\pep\utilhintpeptest.py:367: BeartypeDecorHintPepDeprecatedWarning: PEP type hint typing.List[__main__.DbEntry] deprecated by PEP 585. To resolve this, globally replace this hint by the equivalent PEP 585 type hint (e.g., "typing.List[int]" by "list[int]"). See also:
    https://www.python.org/dev/peps/pep-0585
  warn(warning_message, BeartypeDecorHintPepDeprecatedWarning)
C:\Program Files\Python39\lib\site-packages\beartype\_util\hint\pep\utilhintpeptest.py:367: BeartypeDecorHintPepDeprecatedWarning: PEP type hint typing.Tuple[__main__.HintsHeader, typing.List[__main__.Hint]] deprecated by PEP 585. To resolve this, globally replace this hint by the equivalent PEP 585 type hint (e.g., "typing.List[int]" by "list[int]"). See also:
    https://www.python.org/dev/peps/pep-0585
  warn(warning_message, BeartypeDecorHintPepDeprecatedWarning)
C:\Program Files\Python39\lib\site-packages\beartype\_util\hint\pep\utilhintpeptest.py:367: BeartypeDecorHintPepDeprecatedWarning: PEP type hint typing.List[__main__.Hint] deprecated by PEP 585. To resolve this, globally replace this hint by the equivalent PEP 585 type hint (e.g., "typing.List[int]" by "list[int]"). See also:
    https://www.python.org/dev/peps/pep-0585
  warn(warning_message, BeartypeDecorHintPepDeprecatedWarning)
```

**Comment by djhenderson** [comment] 2021-03-05 20:35
These warnings also occur with Python 3.10a6 and Python 3.8.8.

**Comment by leycec** [comment] 2021-03-06 07:09
*Right.* Thanks for the detailed issue report, Doug. We love to see Albertans here because you inhabit a majestic province of rugged mountains, vast forests, and untrammelled beauty. Here in Ontario, we inhabit swamps. It's a bit different. Also, the Albertan spirit is fierce and proud and free and essentially badass in all respects. These are good things. :canada: 

Onward to [PEP 585](https://www.python.org/dev/peps/pep-0585) deprecations, because everything is *mostly* working as intended here despite being *really* annoying for unfortunate end users such as yourself. If you've stumbled across [official documentation for the `typing` module recently](https://docs.python.org/3/library/typing.html#typing.Tuple), you may have already noticed a stunning  mess of deprecation graffiti like:

> `typing.Tuple`
>     ...
>     *Deprecated since version 3.9:* `builtins.tuple` now supports `[]`. See PEP 585 and Generic Alias Type.

What's going on here? Let's first start at [PEP 484](https://www.python.org/dev/peps/pep-0484) – the beginning of the end. PEP 484 defined the `typing` module and (most) everything in that module, enabling us to annotate complex data structures with type hints like:

```
from typing import List
def muh_rowdy_func(muh_crazy_param: List[List[List[str]]]) -> List[List[List[str]]]:
    return muh_crazy_param
```

So far, so sensible. **PEP 585 deprecated all of that.** The above code snippet that works in Python 3.6—3.10? Yeah. That's gonna break in four years, because that's deprecated and officially going away in four years. Instead, PEP 585 wants you to this **under Python ≥ 3.9**:

```
def muh_rowdy_func(muh_crazy_param: list[list[list[str]]]) -> list[list[list[str]]]:
    return muh_crazy_param
```

So, we no longer parametrize `typing.List`, because `typing.List` is going away in four years. Instead, we just parametrize `list` itself. Of course, [that only currently works in Python 3.9 and 3.10 for reasons that I yell about elsewhere](https://stackoverflow.com/questions/62871524/is-pep-585-unusable-at-runtime-under-python-3-7-and-3-8).

PEP 585 doesn't just deprecate most of `typing`, though. It *also* instructs type checkers such as ourselves to inform end users such as yourself that this is happening, so that you can prepare for the inevitable breakage in four years:

> Importing those [*basically, everything*] from `typing` is deprecated. Due to PEP 563 and the intention to minimize the runtime impact of typing, this deprecation will not generate `DeprecationWarnings`. Instead, **type checkers may warn about such deprecated usage when the target version of the checked program is signalled to be Python 3.9 or newer.** It's recommended to allow for those warnings to be silenced on a project-wide basis.

> **The deprecated functionality will be removed from the `typing` module in the first Python version released 5 years after the release of Python 3.9.0.**

So far, so annoying. Remember how I wrote "everything is *mostly* working as intended here" above, though? Yeah. We're now getting to the *mostly* part.

**You should only have received that warning under Python 3.9 and Python 3.10.** But you received that warning under Python 3.8 too, which isn't right. PEP 585 isn't usable under Python 3.8, so you should *not* have received a deprecating warning there.

I can't actually replicate this on my end, which is sad. It's theoretically possible we're detecting Python versions incorrectly under Windows, but... I kinda doubt that. If we were detecting Python versions incorrectly under Windows, continuous integration (CI) would fail under Windows, but CI passes under Windows. It is a paradox.

Would you mind running the following command under your Windows versions of Python 3.8 and kindly reporting back here with the output?

```
python3.8 -c 'import sys; print(sys.version_info)'
```

Here's what I see when I run that on my Gentoo Linux devbox, for example:

```
$ python3.8 -c 'import sys; print(sys.version_info)'
sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
$ python3.9 -c 'import sys; print(sys.version_info)'
sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
```

Thanks again for considering `beartype` for all your runtime type-checking needs. We'll get you sorted, Doug.

**Comment by djhenderson** [comment] 2021-03-06 19:25
Thanks for the detailed response. It looks like your Python3.9 is returning `sys.version_info` for 3.8 ?? Does your Gentoo use the alternatives system or leave it up to you to name the right executable?

**Cygwin**
I also use cygwin which creates a Posix environment on windows. It is intended to mimic Linux as closely as possible.

```
$ /usr/sbin/alternatives --display python
python - status is auto.
 link currently points to /usr/bin/python3.8
/usr/bin/python2.7 - priority 27
/usr/bin/python3.8 - priority 38
/usr/bin/python3.6 - priority 36
/usr/bin/python3.7 - priority 37
Current `best' version is /usr/bin/python3.8.
```
```
$ python3 -V
Python 3.8.7
```
This is the imports in my app:
```
$ head depchecker.py
#! python3

from typing import Any, Dict, List, Set, Tuple
import dataclasses
from dataclasses import dataclass
import io
from beartype import beartype
```
I do not get the warnings from python 3.8.7, using `-X dev` or `$ export PYTHONDEVMODE=1`, so it looks like the warning behaviour has changed between 3.8.7 and 3.8.8. That is unexpected!


**Windows**
I use the windows python launcher. I don't show anything for python 3.7 because my program uses the walrus operator which is not in 3.7, so it won't compile
```
> py -0p
Installed Pythons found by py Launcher for Windows
 -3.10-64       C:\Users\Doug\AppData\Local\Programs\Python\Python310\python.exe
 -3.9-64        C:\Program Files\Python39\python.exe *
 -3.8-64        C:\Program Files\Python38\python.exe
 -3.7-64        C:\Program Files\Python37\python.exe
```

```
> py -3.8 -V   &&   py -3.9 -V   &&   py -3.10 -V
Python 3.8.8
Python 3.9.2
Python 3.10.0a6
```

```
> py -3.8 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

> py -3.9 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

> py -3.10 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=10, micro=0, releaselevel='alpha', serial=6)
```

And just for reference
```
> where python
C:\Program Files\Python39\python.exe
> pathlist
   1:   C:\Program Files\Python39\Scripts\
   2:   C:\Program Files\Python39\
```
I have no other python in my path.

**Question**
Would doing something like `List = list`, etc instead of importing typing.List in your code where you can use `list[]`, etc. for annotations work?

BTW, does `beartype` check variable annotations? I did not see any mention in the doc.

**Comment by leycec** [comment] 2021-03-07 02:35
> Thanks for the detailed response.

Thank *you*. No, really! You've taken precious time out of first your Friday and now Saturday for our humble project. I appreciate it. :+1: 

> It looks like your Python3.9 is returning `sys.version_info` for 3.8 ??

You are, of course, correct. That was a copy-and-paste [PEBKAC](https://www.computerhope.com/jargon/p/pebkac.htm) due to me being up so late that Friday night became Saturday morning. Gentoo's Python3.9 is thankfully working as intended; here's the actual output:

```
$ python3.8 -c 'import sys; print(sys.version_info)'
sys.version_info(major=3, minor=8, micro=7, releaselevel='final', serial=0)
$ python3.9 -c 'import sys; print(sys.version_info)'
sys.version_info(major=3, minor=9, micro=7, releaselevel='final', serial=0)
```

<sup>*phew*</sup>

> Does your Gentoo use the alternatives system or leave it up to you to name the right executable?

**I'm so glad you asked,** but you might not be in about five seconds. Gentoo Linux actually has its own homegrown solution for installing multiple versions of the same underlying software. We call this stupefying technology [**slots**](https://devmanual.gentoo.org/general-concepts/slotting/index.html).

Slots dramatically simplify developer workflow. For example, slots means that Python developers can trivially install multiple versions of multiple Python interpreters *and* multiple versions of multiple Python packages for those multiple interpreters with a single command. After doing so, the Gentoo system package manager `emerge` will then automatically update those Python interpreters and packages on each system update.

Here is me installing mypy under CPython 3.7, 3.8, and 3.9 with a single command:

```
$ emerge mypy
These are the packages that would be merged:

Calculating dependencies                      ... done!         
[ebuild   R   ~] dev-python/mypy-0.800::gentoo  USE="-doc -test" PYTHON_TARGETS="python3_7 python3_8 python3_9" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No]
```

Gentoo thus installs, updates, and manages `python3.7, `python3.8`, `python3.9`, and `pypy3` commands for me on my behalf – along with Python packages isolated to each of those commands. It's like `pyenv` **+** `venv`, only automated at the OS level.

Command-line wizardry just gets no hotter than that.

*...back to reality.*

> I also use cygwin which creates a Posix environment on windows. It is intended to mimic Linux as closely as possible.

Yes! I love Cygwin! I was fairly active in the [Babun](https://babun.github.io) community, until I reluctantly acknowledged that the [Big List Of Dodgy Apps (BLODA)](https://cygwin.com/faq/faq.html#faq.using.bloda) made Cywin and thus Babun effectively unusable.

Then the Windows Subsystem for Linux (WSL), which suffered no such conflicts, landed. But I commend you for sticking with Cygwin. I certainly have fond memories of it – up until the End.

```
$ python3 -V
Python 3.8.7
```

```
> py -3.8 -V   &&   py -3.9 -V   &&   py -3.10 -V
Python 3.8.8
Python 3.9.2
Python 3.10.0a6
```

```
> py -3.8 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

> py -3.9 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=9, micro=2, releaselevel='final', serial=0)

> py -3.10 -c "import sys; print(sys.version_info)"
sys.version_info(major=3, minor=10, micro=0, releaselevel='alpha', serial=6)
```

This looks sane.

> I do not get the warnings from python 3.8.7, using `-X dev` or `$ export PYTHONDEVMODE=1`, so it looks like the warning behaviour has changed between 3.8.7 and 3.8.8. That is unexpected!

That looks insane.

`beartype` *does* contain conditional logic dependent on the current **minor Python version** (e.g., the `9` in `3.9.1`), because `typing` support, syntax, and semantics typically change a ton across minor Python versions. `beartype` does *not* contain conditional logic dependent on the current **patch Python version** (e.g., the `1` in `3.9.1`), because nothing is supposed to change across patch Python versions.

Moreover, I'm fairly (but *not* entirely) certain that the implementation of the Python Development Mode (PDM) also does *not* significantly change across patch Python versions (e.g., going from 3.8.7 to 3.8.8).

That behaviour is inexplicable. We're probably to blame, because we usually are. Still... I'm having trouble thinking of a plausible explanation for what you're seeing. Urgh!

> Would doing something like `List = list`, etc instead of importing `typing.List` in your code where you can use `list[]`, etc. for annotations work?

**Ah, right.** Unfortunately, the specific issue with PEP 585 deprecations under Python ≥ 3.9 isn't in *our* code as such; the issue is in *your* code, because your code is importing deprecated type hints under Python ≥ 3.9 that will be removed in four years. `typing.List`, for example, will be going away shortly.

There's not much any of us can do about that except yell at official Python developers on their mailing lists and bug trackers. I suspect they're likely to ignore us, though.

The only issue here is that you're seeing a deprecation under Python 3.8 that you shouldn't. But... that's probably not the worst thing to ever happen. Now that you're duly apprised and aware of PEP 585 deprecations, my advice would be to either:

* **Drop Python 3.8 support** and **use PEP 585-style type hints instead.** PEP 585-style type hints (e.g., `list[str]`) aren't usable under Python 3.8, but they're the future. Migrating from PEP 484-style type hints (e.g., `typing.List[str]`) is non-trivial, so it might make sense to pay that price now when it's easier rather than later when it's harder. Ugh!
* **Hide the deprecation warning.** Obviously, this is the easiest option. Here's how to globally and permanently do that in only three lines of Python:

```
from beartype.roar import BeartypeDecorHintPepDeprecatedWarning
import warnings
warnings.simplefilter(action='ignore', category=BeartypeDecorHintPepDeprecatedWarning)
```

**Comment by djhenderson** [comment] 2021-03-07 21:43
My apologies, the problem is in my code rather than the beartype code. When I add the following, my problem goes away.

```
# handle type annotation changes in PEP 3107, 484, 526, 544, 560, 563, 585 
if (
    (sys.version_info.major > 3) or
    (sys.version_info.major == 3 and (sys.version_info.minor > 8) or
    (sys.version_info.minor == 8 and sys.version_info.micro >= 8)
):
    Dict = dict
    List = list
    Set = set
    Str = str
    Tuple = tuple
    from typing import Any # I'm not sure what this should be

else:
    from typing import Any, Dict, List, Set, Tuple
```
Thanks for your detailed responses.

And thanks for your package. I have used mypy in the past, and found that to be a bit clumsy to use (not the program itself, just the usage). It would not be a problem if I was using an automated workflow, but a great deal of my development is for my own private use so most of my git repositories (when I have on) are on BitBucket which allows multiple private repositories for no charge.

**Closed** 2021-03-07 21:43 UTC

**Comment by leycec** [comment] 2021-03-08 06:01
> ...the problem is in my code rather than the beartype code.

You just spoke my favourite eleven contiguous words. :wink: 

Oh, and here's a fun Python tidbit. Did you know that `tuple` actually supports smart integer comparisons out-of-the-box? Since `sys.version_info` is a `tuple`, your three-line test for Python ≥ 3.8.8 can actually be compacted into the following one-liner:

```
# handle type annotation changes in PEP 3107, 484, 526, 544, 560, 563, 585 
if sys.version_info >= (3, 8, 8) :
    Dict = dict
    List = list
    Set = set
    Str = str
    Tuple = tuple
    from typing import Any # I'm not sure what this should be

else:
    from typing import Any, Dict, List, Set, Tuple
```

**Yup.** That actually works. Also, I couldn't help but notice this trailing comment...

```
    from typing import Any # I'm not sure what this should be
```

Right. So, it turns out that [PEP 585](https://www.python.org/dev/peps/pep-0585) only deprecates *most* of the `typing` module. There are still quite a few `typing` attributes that **will probably stick around forever.** These `typing` attributes are *not* deprecated and can be safely depended on regardless of Python version:

* `typing.Any`.
* `typing.Generic`.
* `typing.Hashable`.
* `typing.NewType`.
* `typing.NoReturn`.
* `typing.Optional`.
* `typing.Sizable`.
* `typing.Type`.
* `typing.TypeVar`.
* `typing.Union`.

> And thanks for your package.

Thank *you*, again! This issue helped clarify my thinking on PEP 585. I think I'll reformulate my response above into a [new FAQ answer](https://github.com/beartype/beartype#frequently-asked-questions-faq) to the question: "What does `BeartypeDecorHintPepDeprecatedWarning` mean?"

That's invaluable.

> I have used mypy in the past, and found that to be a bit clumsy to use (not the program itself, just the usage).

You're too polite, Doug. I found mypy to be **Pure Unadulterated Hell** to use. Of 398 "errors" reported by mypy when I first ran it against `beartype 0.5.1`, only 1 actually *was* an error – and even that didn't really matter. I want that week back.

> most of my git repositories (when I have on) are on BitBucket which allows multiple private repositories for no charge.

**Yup.** BitBucket's a good one. GitLab has similar free pricing for private repositories, so naturally my wife and I have at least a dozen in various stages of gestation. Someday, one of those private repositories will become something.

If you ever publicize your work, just ping me with @leycec. I'd love to take a look at what you're doing. I'm sure it's impressive. Thanks again, @djhenderson. Best of luck with Albertan life – and let's hope Spring hits soon. :sun_with_face:

**Comment by leycec** [comment] 2021-03-08 06:42
**Wow!** I just checked out [pywikitree, your impressive Python-based WikiTree API](https://github.com/djhenderson/pywikitree). That's awesome stuff right there. Tracking my wife's genealogy would be equally fascinating and depressing, because her mother's family fled Lithuania during the German-Soviet invasion of World War II on horseback over sickeningly tall mountain ranges that I'd be lucky to even stagger up today. :mount_fuji:
