### ISSUE TITLE
[Bug] PyPy incompatibility with edge-case negative object identifiers

### ISSUE THREAD

**Issue by jvesely** [beartype/beartype#232] opened 2023-04-17 15:55 UTC
the same code runs ok in python 3.7/8/9 but throw the following exception in pypy3.9 7.3.11.
```
conftest.py:5: in <module>
    import psyneulink
psyneulink/__init__.py:35: in <module>
    from . import core  # noqa: E402
psyneulink/core/__init__.py:1: in <module>
    from . import components
psyneulink/core/components/__init__.py:31: in <module>
    from . import mechanisms
psyneulink/core/components/mechanisms/__init__.py:1: in <module>
    from . import modulatory
psyneulink/core/components/mechanisms/modulatory/__init__.py:2: in <module>
    from psyneulink.core.components.mechanisms.modulatory.control import controlmechanism, gating
psyneulink/core/components/mechanisms/modulatory/control/__init__.py:1: in <module>
    from . import defaultcontrolmechanism
psyneulink/core/components/mechanisms/modulatory/control/defaultcontrolmechanism.py:42: in <module>
    from psyneulink.core.components.mechanisms.processing.objectivemechanism import ObjectiveMechanism
psyneulink/core/components/mechanisms/processing/__init__.py:6: in <module>
    from . import transfermechanism
psyneulink/core/components/mechanisms/processing/transfermechanism.py:918: in <module>
    class TransferMechanism(ProcessingMechanism_Base):
psyneulink/core/components/mechanisms/processing/transfermechanism.py:1304: in TransferMechanism
    prefs: Optional[ValidPrefSet] = None,
../pypy3-venv/lib/pypy3.9/site-packages/beartype/_decor/_cache/cachedecor.py:77: in beartype
    return beartype_object(obj, conf)
../pypy3-venv/lib/pypy3.9/site-packages/beartype/_decor/decorcore.py:256: in beartype_object
    return _beartype_func(  # type: ignore[return-value]
../pypy3-venv/lib/pypy3.9/site-packages/beartype/_decor/decorcore.py:694: in _beartype_func
    func_wrapper = make_func(
../pypy3-venv/lib/pypy3.9/site-packages/beartype/_util/func/utilfuncmake.py:255: in make_func
    raise exception_cls(
E   beartype.roar.BeartypeDecorWrapperException: @beartyped __init__() wrapper unparseable, as @beartype generated invalid code raising "SyntaxError: invalid syntax (<@beartype(psyneulink.core.components.mechanisms.processing.transfermechanism.TransferMechanism.__init__) at 0x563ae268bd80>, line 9)":
E
E   (line 0001) def __init__(
E   (line 0002)     *args,
E   (line 0003)     __beartype_func=__beartype_func,
E   (line 0004)     __beartype_conf=__beartype_conf,
E   (line 0005)     __beartype_get_violation=__beartype_get_violation,
E   (line 0006)     __beartype_object_94810843862208=__beartype_object_94810843862208,
E   (line 0007)     __beartype_object_94810825101616=__beartype_object_94810825101616,
E   (line 0008)     __beartype_object_94810830632784=__beartype_object_94810830632784,
E   (line 0009)     __beartype_object_-965=__beartype_object_-965,
E   (line 0010)     __beartype_object_94810891800770=__beartype_object_94810891800770,
E   (line 0011)     __beartype_object_-997=__beartype_object_-997,
E   (line 0012)     __beartype_object_94810891800706=__beartype_object_94810891800706,
E   (line 0013)     __beartype_object_94810891800674=__beartype_object_94810891800674,
E   (line 0014)     __beartype_object_94810891800642=__beartype_object_94810891800642,
E   (line 0015)     __beartype_object_94810843863664=__beartype_object_94810843863664,
E   (line 0016)     __beartype_object_94810849153552=__beartype_object_94810849153552,
E   (line 0017)     **kwargs
E   (line 0018) ):
E   (line 0019)     # Localize the number of passed positional arguments for efficiency.
E   (line 0020)     __beartype_args_len = len(args)
E   (line 0021)     # Localize this positional or keyword parameter if passed *OR* to the
E   (line 0022)     # sentinel "__beartype_raise_exception" guaranteed to never be passed.
E   (line 0023)     __beartype_pith_0 = (
E   (line 0024)         args[3] if __beartype_args_len > 3 else
E   (line 0025)         kwargs.get('input_ports', __beartype_get_violation)
E   (line 0026)     )
E   (line 0027)
E   (line 0028)     # If this parameter was passed...
E   (line 0029)     if __beartype_pith_0 is not __beartype_get_violation:
E   (line 0030)         # Type-check this passed parameter or return value against this
E   (line 0031)         # PEP-compliant type hint.
E   (line 0032)         if not (
E   (line 0033)             # True only if this pith is of one of these types.
E   (line 0034)             isinstance(__beartype_pith_0, __beartype_object_94810843862208)
E   (line 0035)         ):
E   (line 0036)             raise __beartype_get_violation(
E   (line 0037)                 func=__beartype_func,
E   (line 0038)                 conf=__beartype_conf,
E   (line 0039)                 pith_name='input_ports',
E   (line 0040)                 pith_value=__beartype_pith_0,
E   (line 0041)             )
E   (line 0042)
E   (line 0043)     # Localize this positional or keyword parameter if passed *OR* to the
E   (line 0044)     # sentinel "__beartype_raise_exception" guaranteed to never be passed.
E   (line 0045)     __beartype_pith_0 = (
E   (line 0046)         args[13] if __beartype_args_len > 13 else
E   (line 0047)         kwargs.get('termination_threshold', __beartype_get_violation)
E   (line 0048)     )
E   (line 0049)
E   (line 0050)     # If this parameter was passed...
E   (line 0051)     if __beartype_pith_0 is not __beartype_get_violation:
E   (line 0052)         # Type-check this passed parameter or return value against this
E   (line 0053)         # PEP-compliant type hint.
E   (line 0054)         if not (
E   (line 0055)             # True only if this pith is of one of these types.
E   (line 0056)             isinstance(__beartype_pith_0, __beartype_object_94810825101616)
E   (line 0057)         ):
E   (line 0058)             raise __beartype_get_violation(
E   (line 0059)                 func=__beartype_func,
E   (line 0060)                 conf=__beartype_conf,
E   (line 0061)                 pith_name='termination_threshold',
E   (line 0062)                 pith_value=__beartype_pith_0,
E   (line 0063)             )
E   (line 0064)
E   (line 0065)     # Localize this positional or keyword parameter if passed *OR* to the
E   (line 0066)     # sentinel "__beartype_raise_exception" guaranteed to never be passed.
E   (line 0067)     __beartype_pith_0 = (
E   (line 0068)         args[14] if __beartype_args_len > 14 else
E   (line 0069)         kwargs.get('termination_comparison_op', __beartype_get_violation)
E   (line 0070)     )
E   (line 0071)
E   (line 0072)     # If this parameter was passed...
E   (line 0073)     if __beartype_pith_0 is not __beartype_get_violation:
E   (line 0074)         # Type-check this passed parameter or return value against this
E   (line 0075)         # PEP-compliant type hint.
E   (line 0076)         if not (
E   (line 0077)             # True only if this pith is of one of these types.
E   (line 0078)             isinstance(__beartype_pith_0, __beartype_object_94810830632784) or
E   (line 0079)             (
E   (line 0080)                 # True only if this pith is of one of these literal types.
E   (line 0081)                 isinstance(__beartype_pith_0, str) and (
E   (line 0082)                     # True only if this pith is equal to this literal.
E   (line 0083)                     __beartype_pith_0 == __beartype_object_-965 or
E   (line 0084)                     # True only if this pith is equal to this literal.
E   (line 0085)                     __beartype_pith_0 == __beartype_object_94810891800770 or
E   (line 0086)                     # True only if this pith is equal to this literal.
E   (line 0087)                     __beartype_pith_0 == __beartype_object_-997 or
E   (line 0088)                     # True only if this pith is equal to this literal.
E   (line 0089)                     __beartype_pith_0 == __beartype_object_94810891800706 or
E   (line 0090)                     # True only if this pith is equal to this literal.
E   (line 0091)                     __beartype_pith_0 == __beartype_object_94810891800674 or
E   (line 0092)                     # True only if this pith is equal to this literal.
E   (line 0093)                     __beartype_pith_0 == __beartype_object_94810891800642
E   (line 0094)             ))
E   (line 0095)         ):
E   (line 0096)             raise __beartype_get_violation(
E   (line 0097)                 func=__beartype_func,
E   (line 0098)                 conf=__beartype_conf,
E   (line 0099)                 pith_name='termination_comparison_op',
E   (line 0100)                 pith_value=__beartype_pith_0,
E   (line 0101)             )
E   (line 0102)
E   (line 0103)     # Localize this positional or keyword parameter if passed *OR* to the
E   (line 0104)     # sentinel "__beartype_raise_exception" guaranteed to never be passed.
E   (line 0105)     __beartype_pith_0 = (
E   (line 0106)         args[15] if __beartype_args_len > 15 else
E   (line 0107)         kwargs.get('output_ports', __beartype_get_violation)
E   (line 0108)     )
E   (line 0109)
E   (line 0110)     # If this parameter was passed...
E   (line 0111)     if __beartype_pith_0 is not __beartype_get_violation:
E   (line 0112)         # Type-check this passed parameter or return value against this
E   (line 0113)         # PEP-compliant type hint.
E   (line 0114)         if not (
E   (line 0115)             # True only if this pith is of one of these types.
E   (line 0116)             isinstance(__beartype_pith_0, __beartype_object_94810843863664)
E   (line 0117)         ):
E   (line 0118)             raise __beartype_get_violation(
E   (line 0119)                 func=__beartype_func,
E   (line 0120)                 conf=__beartype_conf,
E   (line 0121)                 pith_name='output_ports',
E   (line 0122)                 pith_value=__beartype_pith_0,
E   (line 0123)             )
E   (line 0124)
E   (line 0125)     # Localize this positional or keyword parameter if passed *OR* to the
E   (line 0126)     # sentinel "__beartype_raise_exception" guaranteed to never be passed.
E   (line 0127)     __beartype_pith_0 = (
E   (line 0128)         args[18] if __beartype_args_len > 18 else
E   (line 0129)         kwargs.get('prefs', __beartype_get_violation)
E   (line 0130)     )
E   (line 0131)
E   (line 0132)     # If this parameter was passed...
E   (line 0133)     if __beartype_pith_0 is not __beartype_get_violation:
E   (line 0134)         # Type-check this passed parameter or return value against this
E   (line 0135)         # PEP-compliant type hint.
E   (line 0136)         if not (
E   (line 0137)             # True only if this pith is of one of these types.
E   (line 0138)             isinstance(__beartype_pith_0, __beartype_object_94810849153552) or
E   (line 0139)             isinstance(__beartype_pith_0, dict)
E   (line 0140)         ):
E   (line 0141)             raise __beartype_get_violation(
E   (line 0142)                 func=__beartype_func,
E   (line 0143)                 conf=__beartype_conf,
E   (line 0144)                 pith_name='prefs',
E   (line 0145)                 pith_value=__beartype_pith_0,
E   (line 0146)             )
E   (line 0147)
E   (line 0148)     # Call this function with all passed parameters and return the value
E   (line 0149)     # returned from this call.
E   (line 0150)     return __beartype_func(*args, **kwargs)
```

**Comment by leycec** [comment] 2023-04-18 05:13
**Holy flaming balls of just-in-time optimization.** Oh, that's _bad_. Like, super-terri-_bad_.

Thankfully, you're awesome, @jvesely. You included the full exception message. Because you went above and beyond the call of open-source duty, **I can theoretically fix this for you tonight.** Theoretically, anyway. I can't reliably reproduce this, which means I can't reliably test this, which means I guarantee nothing but promise everything.

## PyPy: What You Doin', Bro!?!?

First, here's our problem:

```python
def __init__(
    *args,
    __beartype_func=__beartype_func,
    __beartype_conf=__beartype_conf,
    __beartype_get_violation=__beartype_get_violation,
    __beartype_object_94810843862208=__beartype_object_94810843862208,
    __beartype_object_94810825101616=__beartype_object_94810825101616,
    __beartype_object_94810830632784=__beartype_object_94810830632784,
    __beartype_object_-965=__beartype_object_-965,  # <-- WUT THE HECK.
    __beartype_object_94810891800770=__beartype_object_94810891800770,
    __beartype_object_-997=__beartype_object_-997,  # <-- WUT THE HECK: Part II.
    __beartype_object_94810891800706=__beartype_object_94810891800706,
    __beartype_object_94810891800674=__beartype_object_94810891800674,
    __beartype_object_94810891800642=__beartype_object_94810891800642,
    __beartype_object_94810843863664=__beartype_object_94810843863664,
    __beartype_object_94810849153552=__beartype_object_94810849153552,
    **kwargs
):
```

Clearly, `__beartype_object_-965` and `__beartype_object_-997` are invalid parameter names. @beartype is erroneously generating a type-checking wrapper accepting parameters with invalid names. But... why? I can explain exactly what's happening here, but the truth may shock you.

## @beartype: What You Doin' Too, Bro!?!?

Here's the responsible line in the @beartype codebase erroneously generating the above parameter names:

```python
    # Name of the new attribute referring to this object in this scope, mildly
    # obfuscated so as to avoid name collisions.
    attr_name = f'__beartype_object_{id(attr)}'
```

Trivial, right? @beartype just synthesizes parameter names by deferring to the `id()` builtin, which returns an integer uniquely identifying the passed object. Under CPython, this integer is guaranteed to be a memory address and thus non-negative (i.e., `id(obj) >= 0` for all objects `obj`). The above situation *never* arises under CPython.

Under PyPy, however, this guarantee does *not* appear to hold. PyPy appears to be identifying a small handful of objects with negative numbers. Since I've never seen this myself, I'd hate to speculate what sort of objects these might be – but they're probably fairly exotic C-based objects of some sort. PyPy object identifiers are *supposed* to be non-negative indices into arrays. Clearly, that's *not* a universal guarantee. 

I'm both stunned and appalled that PyPy returns negative object identifiers in non-deterministic edge cases. Nonetheless, we don't make the rules; we just break them and then openly mock PyPy.

## @leycec: You Still Talkin', Bro?

No. No, I'm done. I think I have a case of the Mondays now. :sob:

**Comment by leycec** [comment] 2023-04-18 06:06
**Resolved by 0c3dc53...** I _think_. Would testing this locally be feasible for you, @jvesely? It'd be awesome if you locally ensure I actually did fix this by installing this commit under PyPy: e.g.,

```
pypy -m pip install git+https://github.com/beartype/beartype.git@0c3dc53cbcfec12e91a408724e509b2b4014e5a7
```

If not, no worries. But this is a serious incompatibility. I'll need to push out a new release with this fix in a day or two under the assumption that it does actually fix something. Let's pretend I know what I'm doing here. The sweat dripping off my hooked nose is palpable. :sweat_smile:

**Closed by leycec** 2023-04-18 06:06 UTC

**Comment by jvesely** [comment] 2023-04-18 13:55
> **Resolved by [0c3dc53](https://github.com/beartype/beartype/commit/0c3dc53cbcfec12e91a408724e509b2b4014e5a7)...** I _think_. Would testing this locally be feasible for you, @jvesely? It'd be awesome if you locally ensure I actually did fix this by installing this commit under PyPy: e.g.,
> 
> ```
> pypy -m pip install git+https://github.com/beartype/beartype.git@0c3dc53cbcfec12e91a408724e509b2b4014e5a7
> ```
> 
> If not, no worries. But this is a serious incompatibility. I'll need to push out a new release with this fix in a day or two under the assumption that it does actually fix something. Let's pretend I know what I'm doing here. The sweat dripping off my hooked nose is palpable. sweat_smile

Thank you for an awesome response and an even more awesome fix.
I can confirm that installing the above git commit makes pypy run happily with beartype.

**Comment by jvesely** [comment] 2023-04-28 16:11
> **Awesome secret sauce.** Thanks so much for the rapid confirmation, @jvesely. I'll release `beartype 0.13.2` first thing tonight. Go, Team Bear! Go! horse_racing dash

Hi, is there an ETA for the awesome release?

**Comment by leycec** [comment] 2023-04-28 19:12
**Gah!** You're right. I am dropping the ball like a juggler with greased fingers on Mardi Gras. Ideally, I'd release this tonight; instead, we're *soooooo* close to [PEP 673 (i.e., `typing.Self`)](https://peps.python.org/pep-0673) support that I'll probably end up obsessing about that tonight until I pass out from oxidative stress release.

So...  **Monday?** `beartype 0.14.0` will land on Monday with this! It is my solemn promise. :crossed_fingers: :crossed_fingers:
