### ISSUE TITLE
You gotta keep ’em iterated

### ISSUE THREAD

**Issue by posita** [beartype/beartype#65] opened 2021-10-28 13:49 UTC
(With apologies to The Offspring.)

So, I'm…_lazy_. I work _really_ hard at it. (I'm likely [not the only one](https://xkcd.com/1319/).) Once upon a time, when I was new to Python typing, spending hours reading about generators, iterables, iterators, sequences, etc., instead of minutes coding up what I needed to … . Wait. You know what? For once, I'm **_not_** going to craft another impromptu episode of _Time for a Trivial Moral That Didn’t Benefit a Lick by Being Buried at the End of a Long, Rambling Story but Instead Could Have and Should Have Led, Because at Least the Audience Would Have Been Awake at the Time™_. (Title capitalization [verified](https://capitalizemytitle.com/), so you know it's authentic.)

Anyhoo, [_this_](https://docs.python.org/3/library/typing.html#typing.Generator):

> A generator can be annotated by the generic type `Generator[YieldType, SendType, ReturnType]`. … [¶] … [¶] Alternatively, annotate your generator as having a return type of either `Iterable[YieldType] or Iterator[YieldType]` … .

Now [you and I both know](https://github.com/beartype/beartype/pull/41#issuecomment-880349445) that taking certain parts of the standard library documentation at face value can lead to great sadness, but I _think_ the quoted statement is legit in spirit, at least insofar as [iterators do appear to be subsets of generators](https://docs.python.org/3/library/collections.abc.html?highlight=rator#collections-abstract-base-classes). 

_[sweeping gesture to divert attention away from the fact that immediately after conceding that Python's docs were not necessarily trustworthy, evidence presented in support of why they should be trusted in this case came from those very same docs]_
![magic!](https://c.tenor.com/P_59o7Z_xO8AAAAM/change-arrested-development.gif)

Over my career, I would conservatively estimate that typing `Iterator[Foo]` instead of `Generator[Foo, None, None]` has saved me [_dozens_](https://youtu.be/lKie-vgUGdI) of precious seconds that I would have never been able to squander on one fifth of one YouTube video recommendation that briefly compelled me to sit—motionless—until its banal end, but of which I now possess no memory.

My point is that my code is littered with stuff like this:

``` python
def ima_generator_fool(…) -> Iterator[…]:
    …
    yield …
    …
```

Sadly, with 0.9.0, I must now account for my sloth:

``` python
# test_case.py
from __future__ import annotations
from collections.abc import Generator, Iterator, Sequence
from beartype import __version__ as beartype_version
from beartype import beartype
print(beartype_version)

@beartype
def silly_rator1(seq: Sequence) -> Generator:  # <-- Generator works ...
    yield from seq

@beartype
def silly_rator2(seq: Sequence) -> Iterator:  # <-- ... but Iterator fails
    yield from seq
```

``` sh
% PYTHONWARNINGS=ignore python test_case.py
0.9.0
Traceback (most recent call last):
  File "/Users/matt/Documents/dev/dycelib/test_case.py", line 9, in <module>
    def silly_rator1(seq: Sequence) -> Generator:  # <-- Generator works ...
  File "/Users/matt/.acct/.virtualenvs/dycelib/lib/python3.9/site-packages/beartype/_decor/main.py", line 159, in beartype
    func_wrapper_code = generate_code(func_data)
  File "/Users/matt/.acct/.virtualenvs/dycelib/lib/python3.9/site-packages/beartype/_decor/_code/codemain.py", line 170, in generate_code
    code_check_return = _code_check_return(data)
  File "/Users/matt/.acct/.virtualenvs/dycelib/lib/python3.9/site-packages/beartype/_decor/_code/codemain.py", line 450, in _code_check_return
    hint = reduce_hint_pep484585_func_return(func)
  File "/Users/matt/.acct/.virtualenvs/dycelib/lib/python3.9/site-packages/beartype/_util/hint/pep/proposal/pep484585/utilpep484585func.py", line 129, in reduce_hint_pep484585_func_return
    _die_of_hint_return_invalid(
  File "/Users/matt/.acct/.virtualenvs/dycelib/lib/python3.9/site-packages/beartype/_util/hint/pep/proposal/pep484585/utilpep484585func.py", line 182, in _die_of_hint_return_invalid
    raise exception_cls(
beartype.roar.BeartypeDecorHintPep484585Exception: @beartyped generator silly_rator1() return type hint <class 'collections.abc.Generator'> contextually invalid (i.e., expected either collections.abc.Generator[...] or typing.Generator[...] type hint)..
```

FYI, Importing from `typing` instead of `collections.abc` has the same effect. This worked in 0.8.1:

``` python
% PYTHONWARNINGS=ignore python test_case.py
0.8.1
```

Also, Mypy doesn't complain, and I [vaguely recall a great man once saying](https://github.com/beartype/beartype/issues/38#issuecomment-871051126), "What Mypy does, [`beartype`] do."

**Comment by leycec** [comment] 2021-10-30 05:36
**Resolved by 79e9b9f,** the commit whose hash contains a probabilistically unlikely number of 9s. This can only mean I have listened to one too many [cybergrind LPs](https://rateyourmusic.com/genre/cybergrind) <sup>**←NSFW!** Do *not* click the prior link. It's not my fault?</sup> tonight and must now shovel food into my ageing face and pass out.

`cybergrind:` *betcha didnt even know that was a thing.*

**Closed by leycec** 2021-10-30 05:36 UTC

**Comment by posita** [comment] 2021-10-31 14:40
> This is the Python equivalent of [Russian chatbot agitprop](https://en.wikipedia.org/wiki/Agitprop).

What's the saying? Never assume malice when ~incompetence~ _a lack of proper incentives_ would suffice? My guess is that oversight is an artifact of a PEP's purpose. While it _looks_ like an RFC or W3C standard, I am slowly coming to the understanding that it's more of a pitch to convince gatekeepers to let in a feature or behavior change. That audience likely fills in any missing content without even realizing it. I should have come to this realization much earlier, since that is ~well~ _technically_ documented in one of the dozen-or-so of PEPs-about-PEPs. From [PEP 1](https://www.python.org/dev/peps/pep-0001/#pep-audience):

> **PEP Audience**
>
> The typical primary audience for PEPs are the core developers of the CPython reference interpreter and their elected Steering Council, as well as developers of other implementations of the Python language specification.

Of course, that section immediately goes on to say:

> However, other parts of the Python community may also choose to use the process (particularly for Informational PEPs) to document expected API conventions and to manage complex design coordination problems that require collaboration across multiple projects.

Despite the abundance—nay, _glut_— of process docs, I have (so far) found little guidance on how PEP authors should distinguish among these these subtle-but-important differences. As with "[relatively defenseless animals [that take] on the appearance of [others with] better defenses](http://pigeon.psy.tufts.edu/avc/zentall/default.htm#species)", it can be difficult to tell.

![viceroy](http://pigeon.psy.tufts.edu/avc/zentall/images/defaul3.jpg) ![monarch](http://pigeon.psy.tufts.edu/avc/zentall/images/monarch.jpg)
_Which is the tasty specification on which others may depend as a source of truth and clarity, and which is the bitter manifesto designed to cultivate political influence? As with other questions, [the world may never know](https://youtu.be/O6rHeD5x2tI)._

I got bored of reading about the process of improving process and went back to my life as a peasant non pedant and have been much happier. This was in no small part due to my reliance on @leycec and Team Spen to do the real work, affording me the freedom to casually manufacture side commentary.

> … [T]he commit whose hash contains a probabilistically unlikely number of 9s

You weren't kidding!

``` python
>>> commit = "79e9b9f3def73888a4c9c99bf0112f491b3b9fca"
>>> from collections import Counter 
>>> c = Counter(commit) ; c
Counter({'9': 8, 'f': 5, 'b': 4, '3': 3, '8': 3, 'c': 3, '1': 3, '7': 2, 'e': 2, 'a': 2, '4': 2, 'd': 1, '0': 1, '2': 1})
>>> from fractions import Fraction
>>> Fraction(c["9"], len(commit))
Fraction(1, 5)
```

What's also weird is that the 8s are entirely contiguous.

![magic](https://c.tenor.com/YzW0x0k93QUAAAAM/magic.gif)

**Comment by leycec** [comment] 2021-11-01 05:59
> Never assume malice when ~~incompetence~~ a lack of proper incentives would suffice?

But, but, but... I *love* government-corporate-NGO ~~propaganda~~ marketing. That's not malice! That's fun stuff – especially as ~~propaganda~~ marketing never had the intended effect on me it seems to have on others. When someone tells me to do something, I grin, nod, and ask, "Why?" Then someone either punches me, fires me, or pretends I just said posed an existentialist conundrum in Kiswahili. <sup>*Source: used to speak Kiswahili. Boss language.*</sup>

Grizzled bears now presents...

## Best ~~Propaganda~~ Marketing Campaigns of the 1900's and Beyond!

We begin with this infamous double-think post-modern piece from the London Metropolitan Police, which may not have necessarily instilled the confidence in strong-armed law enforcement it was intended to:

![eyes in the sky, bro](https://preview.redd.it/czsxnoezajt31.jpg?auto=webp&s=744c95e196ceff2a813906d58dd584b87219327b)

*oh. shit.* Straight-up Sauron Eye Tower right there. J.R.R. Tolkien rolling his eyes while puffing on herbal blunts in the elvish paradise of Arda.

We continue with this little-known WWII-era Victory Garden poster. Of all of my favourite ~~propaganda~~ public education artwork, Victory Garden memorobilia takes the organic free-range locally sourced cake and devours it. It's so wholesome, feel-good, and homely. Also the only ~~propaganda~~ adult retraining movement that *didn't* require skewering other humans with the sharp ends of pointy bits of metal.

Behold! The pièce de résistance of the Victory Garden moment:

![veggies ftw](https://d3d0lqu00lnqvz.cloudfront.net/media/media/d31cb5a0-3f96-4fd6-b6ad-6be0587d4947.jpg)

Yup. It's anthropomorphic Canadian veggies marching in lockstep. Together, they *will* secure a healthier diet for us all.

**Comment by posita** [comment] 2021-11-01 14:44
> I grin, nod, and ask, "Why?" Then someone either punches me, fires me, or pretends I just said posed an existentialist conundrum in Kiswahili.

You and I must have both had chicken pox the week they taught ~obedience~ _market consumption for great good_ in ~training camp~ _school_. If I had a nickel every time something like what you describe happened to me, I'd probably have a fist full of nickels.
