### ISSUE TITLE
Properly annotating a callable parameter

### ISSUE THREAD

**Issue by mikaelho** [beartype/beartype#93] opened 2022-01-30 10:49 UTC
My apologies if this is a frequently asked question, but searching here and elsewhere did not help.

If I use `typing.Callable`, beartype gives me an ugly warning about deprecation (despite `typing.Callable` not mentioned in PEP 585).
 
Based on the discussion on the PEP 585, I should be able to do this:
`from beartype.typing import Callable`
... but my installation of beartype 0.9.1 does not even find `beartype.typing`.

What am I missing, any recommendations?

**Comment by leycec** [comment] 2022-01-31 06:35
Oh, no apologies needed whatsoever! This is a *great* question, because our upcoming `beartype 0.10.0` release to be published in surely no more than several days (I swear it) will provide exactly the `beartype.typing` API you seek. Of course...

We have yet to publish `beartype 0.10.0`. I humbly and abjectly apologize to you in turn for that. For now, I'm afraid you'll have to [temporarily adopt one of the *other* PEP 585 workarounds instead](https://github.com/beartype/beartype#are-we-on-the-worst-timeline). I recommend typing aliases for robustness: e.g.,

``` python
# In "{your_package}._typing":
from sys import version_info

if version_info >= (3, 9):
    from collections.abc import Callable
else:
    from typing import Callable
```

I acknowledge this is *extremely* annoying. I blame both PEP 585 and myself. If you'll **bear** <sup>...heh</sup> with me, we should have this fully resolved by early February for you and everyone else.

Thanks again for the timely interest, @mikaelho! Let's see how dangerously fast I can shove `beartype 0.10.0` out the door. :smile:

**Comment by leycec** [comment] 2022-01-31 06:36
*marked as duplicate of #81*

**Closed by leycec** 2022-01-31 06:35 UTC

**Comment by mikaelho** [comment] 2022-01-31 17:44
Thank you for the fast, kind, informative and entertaining response.

**Comment by posita** [comment] 2022-01-31 18:37
@mikaelho, if you like to play around with it before its release, you can test the bleeding edge locally with something like:

`pip install git+https://github.com/beartype/beartype.git@main#egg=beartype`

Here's an example for context:

``` sh
% python -m venv --upgrade-deps /tmp/test
Requirement already satisfied: pip in /private/tmp/test/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-22.0.2-py3-none-any.whl (2.1 MB)
…
Successfully installed pip-22.0.2 setuptools-60.6.0
% /tmp/test/bin/pip install 'git+https://github.com/beartype/beartype.git@main#egg=beartype'
Collecting beartype
  Cloning https://github.com/beartype/beartype.git (to revision main) to /private/var/folders/1b/vhw5s1ms7z71xrslggl9whwc0000gn/T/pip-install-yhfcu79e/beartype_34247a76b5b6437aac9b8b93840a4789
  Running command git clone --filter=blob:none --quiet https://github.com/beartype/beartype.git /private/var/folders/1b/vhw5s1ms7z71xrslggl9whwc0000gn/T/pip-install-yhfcu79e/beartype_34247a76b5b6437aac9b8b93840a4789
  Resolved https://github.com/beartype/beartype.git to commit 4190bc3112d0f56d81af586a5f01a10c3e19feae
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for beartype, since package 'wheel' is not installed.
Installing collected packages: beartype
  Running setup.py install for beartype ... done
Successfully installed beartype-0.10.0
% /tmp/test/bin/pip list
Package    Version
---------- -------
beartype   0.10.0
pip        22.0.2
setuptools 60.6.0
```
