### ISSUE TITLE
beartype-0.18.0 is not compatible with dagger-io

### ISSUE THREAD

**Issue by rbnhd** [beartype/beartype#354] opened 2024-04-03 02:13 UTC
After the latest update to 0.18.0, _import dagger_ will throw this error regarding beartype

```
import dagger
--
385 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dagger/__init__.py", line 22, in <module>
386 | from .client.gen import *
387 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dagger/client/gen.py", line 336, in <module>
388 | class Container(Type):
389 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/dagger/client/gen.py", line 349, in Container
390 | @typecheck
391 | ^^^^^^^^^
392 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/decorcache.py", line 130, in beartype_confed
393 | return beartype_object(obj, conf)
394 | ^^^^^^^^^^^^^^^^^^^^^^^^^^
395 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 87, in beartype_object
396 | _beartype_object_fatal(obj, conf=conf, **kwargs)
397 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/decorcore.py", line 136, in _beartype_object_fatal
398 | beartype_nontype(obj, **kwargs)  # type: ignore[return-value]
399 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
400 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 174, in beartype_nontype
401 | return beartype_func(obj, **kwargs)  # type: ignore[return-value]
402 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
403 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/_decornontype.py", line 239, in beartype_func
404 | func_wrapper_code = generate_code(bear_call)
405 | ^^^^^^^^^^^^^^^^^^^^^^^^
406 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/wrap/wrapmain.py", line 118, in generate_code
407 | code_check_params = _code_check_args(bear_call)
408 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^
409 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/wrap/_wrapargs.py", line 309, in code_check_args
410 | reraise_exception_placeholder(
411 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_util/error/utilerrraise.py", line 138, in reraise_exception_placeholder
412 | raise exception.with_traceback(exception.__traceback__)
413 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/wrap/_wrapargs.py", line 205, in code_check_args
414 | _die_if_arg_default_unbearable(
415 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_decor/wrap/_wrapargs.py", line 425, in _die_if_arg_default_unbearable
416 | if is_bearable(
417 | ^^^^^^^^^^^^
418 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/door/_doorcheck.py", line 296, in is_bearable
419 | func_tester = make_func_tester(hint, conf)
420 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
421 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 250, in _callable_cached
422 | raise exception
423 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_util/cache/utilcachecall.py", line 242, in _callable_cached
424 | return_value = args_flat_to_return_value[args_flat] = func(
425 | ^^^^^
426 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_check/checkmake.py", line 180, in make_func_tester
427 | return _make_func_checker(  # type: ignore[return-value]
428 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
429 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_check/checkmake.py", line 726, in _make_func_checker
430 | reraise_exception_placeholder(
431 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_util/error/utilerrraise.py", line 138, in reraise_exception_placeholder
432 | raise exception.with_traceback(exception.__traceback__)
433 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_check/checkmake.py", line 679, in _make_func_checker
434 | get_hint_pep484585_ref_names_relative_to(
435 | File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/beartype/_util/hint/pep/proposal/pep484585/utilpep484585ref.py", line 429, in get_hint_pep484585_ref_names_relative_to
436 | raise exception_cls(
437 | beartype.roar.BeartypeDecorHintForwardRefException: Is_bearable() type hint collections.abc.Sequence['Container'] \| None type hint relative forward reference "Container" currently only type-checkable in type hints annotating @beartype-decorated callables and classes. For your own safety and those of the codebases you love, consider canonicalizing this relative forward reference into an absolute forward reference (e.g., replace "Container" with "{your_package}.{your_submodule}.Container").
```

**Comment by leycec** [comment] 2024-04-03 05:38
**Gah!** This is truly terribad. I am now dejected. @beartype strives to preserve compatibility at all costs. In this case, the cost is my evening. I'm so sorry for the unexpected breakage, @rbnhd. I'll repeatedly bash my head against this tonight and excrete a h0tfix as soon as feasible for an unproductive human such as myself. I sigh. :face_exhaling: 

Also, might I add that [your GitHub avatar is stellar](https://avatars.githubusercontent.com/u/32036969?v=4)! Projecting serious Minos-labyrinth-projected-onto-a-tesseract vibes there.

**Comment by rbnhd** [comment] 2024-04-03 05:51
xD

**Comment by leycec** [comment] 2024-04-03 06:12
@jedevc, @helderco, @wingyplus: I now owe `dagger-io` some heavy apologies for the @beartype 0.18.0 breakage. I'm wringing my hands right now. I see you've wisely pinned `beartype<0.18.0` in your `pyproject.toml`. *Good. This is good.*

Thankfully, I know exactly what's wrong. Because it's the same thing that's *always* wrong:

> "Forward references, how I loathe thee."

I hope to unleash @beartype 0.18.1 with a well-tested fix Tuesday night. Let us believe these seductive words I am saying. It's time to strap on the nerd glasses and bring out the rusty hacksaw again. :nerd_face:

**Comment by leycec** [comment] 2024-04-03 07:15
**Resolved by 7b4976a5964.** Actually, I just disabled the offending functionality. I'll take worky over broke-back @beartype. This issue is sufficiently horrible that I'm *immediately* releasing @beartype 0.18.1 in a few minutes.

Thanks for *bear*ing with us, all. :sob:

**Closed by leycec** 2024-04-03 07:15 UTC

**Comment by leycec** [comment] 2024-04-03 07:32
*Aaaaaaaaaand...* @beartype 0.18.1 is out. I've personally confirmed `dagger` to be importable with @beartype 0.18.1. Balance has now been restored to the force. We return to your regularly scheduled Tuesday. Forgive us for our sins, for we were dumb. :sweat_smile:

**Comment by rbnhd** [comment] 2024-04-03 08:15
@leycec 
Thanks. 
For a moment, I felt a great disturbance in the force, as if millions of bears have been stabbed by daggers and were suddenly silenced.

**Comment by helderco** [comment] 2024-04-03 09:44
@leycec, thanks for the quick revert! 😮‍💨 That's a quicker fix than requiring a new release from us. Yeah our users were quite affected but it was not all bad. 🙂

I took the opportunity to fix a couple of issues with our default values in:
- https://github.com/dagger/dagger/pull/6998

And it was a test for the new pinning/locking capabilities for Python modules added in (but not released yet):
- https://github.com/dagger/dagger/pull/6884

Python doesn't have a [locking standard](https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593/2) yet, which made this more difficult.

**Comment by leycec** [comment] 2024-04-04 23:26
> Yeah our users were quite affected but it was not all bad.

*incredibly diplomatic way of saying*: "It was all bad." :rofl: 

> Python doesn't have a [locking standard](https://discuss.python.org/t/lock-files-again-but-this-time-w-sdists/46593/2) yet, which made this more difficult.

**Fascinating!** `pip` lockfiles is a frighteningly deeper topic than I assumed – sorta like most of @beartype 0.18.0. I'd always thought that was a "solved" problem domain. In 2024, clearly nothing is solved.

Thanks again for your fore*bear*ance with our breakage, @helderco. Tests will be written. Issues will be wrangled. Somehow, @beartype will eventually type-check all your default values at decoration time without blowing itself *or* you up. *Somehow.*
