### ISSUE TITLE
[DOOR Bug] `Tuple` and `Any` Comparision

### ISSUE THREAD

**Issue by wesselb** [beartype/beartype#205] opened 2023-01-15 18:27 UTC
Hey @leycec,

I hope you're doing well! I might have run into another freaky edge case.

This results into an error:

```python
>>> from beartype.door import TypeHint

>>> import typing

>>> TypeHint(typing.Tuple[object, ...]) <= TypeHint(typing.Any)
...
TypeError: typing.Any cannot be used with issubclass()

During handling of the above exception, another exception occurred:

...
TypeError: typing.Any cannot be used with issubclass()
```

Possibly the recursion in `beartype/door/_proposal/pep484585/doorpep484585tuple.py` might need to make use of `TypeHint.__le__` rather than `issubclass`?

**Comment by leycec** [comment] 2023-01-15 23:32
**Doin' so swell!** Thanks so much for asking. The ~~eroded swamp flats~~ "hills" have erupted with filth-encysted snow. My wife and I have taken the fight for fitness to the backwoods trails of Ontario with our trusty rusty cross-country skis, heated gloves that glow in the dark like lithium ion gauntlets of power, and ski masks that make us look creepy. The good times are copious.

And thanks so much for this detailed report that is almost certainly correct about everything. I should *probably* `grep` the DOOR API for other highly suspicious calls to `issubclass()` – but chronic laziness and bad habits suggests that I'll instead play *Hollow Knight* until my head pulsates with a migraine at 5:57AM and I quietly admit to myself that the week is off to a rougher start than usual.

**Comment by leycec** [comment] 2023-01-16 02:29
**Success strikes back!** Surprisingly, it turns out that this is *sorta* a duplicate of #198. We already resolved this without even knowing we were resolving this. To guarantee that I am not lying, I've added yet another unit test exercising this. But... *yeah.* It's mostly worky from what I can tell. 2023: things are already looking up.

We *really* need to excrete a new stable release. I promise delivery of `beartype 0.12.0` with all these fixes and more by this Friday-ish. Of course, you can trust nothing I say. If you'd like to continue thrashing the DOOR API with hard-hitting edge cases, please consider installing the live GitHub-hosted version of @beartype as a temporary measure: e.g.,

```bash
python3 -m pip install git+https://github.com/beartype/beartype.git@784b779289f6ea52c88d8b7dbf014084f790d2e3
```

So sorry for the gruesome delays – and thanks *yet again* for being so attentive to all our failures. We will nail this down to the floor for you and everyone else soon. Would @leycec lie? :face_exhaling:

**Closed by leycec** 2023-01-16 02:29 UTC

**Comment by wesselb** [comment] 2023-01-16 07:05
Whoa, cross-country skiing through the backwood trails of Ontario sounds absolutely blissful. 😌

Thank you so much for the super rapid investigation! I definitely should have tested the latest `master` first. Once I get home I’ll try it out right away, though I have no doubts at all that things will be working beautifully. A good start of 2023 indeed!
