### ISSUE TITLE
[Feature Request] Minimized Exceptions

### ISSUE THREAD

**Issue by bionicles** [beartype/beartype#398] opened 2024-06-23 15:54 UTC
no doubt this is a re-issue, but just wanted to show you what fills my monitor when i enable beartype. the signal to noise ratio is too low, just an infinite wall of tracebacks, sadly gonna have to turn it off

if there is a problem hidden somewhere in a class, ok, great, show us the problem, not the full traceback of bear internals please. 

![image](https://github.com/beartype/beartype/assets/24532336/1fc8ef27-8e20-4dc7-8532-735fae03f892)

![image](https://github.com/beartype/beartype/assets/24532336/f81437e8-8c5f-474d-ad27-d860da685c52)
that's patronizing BS, because there are plenty of reasons to want less verbose beartype besides "SKILL ISSUE", like not having to scroll through pages and pages of beartype exception details to find the name of the class with a problem hidden inside (not helpful)

Is it possible to customize these exceptions so they don't show users beartype internal traceback, only the user code locations in violation of whatever? That's a dealbreaker for me, tbh, it's just too much useless details about how you're making the errors, fills my whole terminal history, I want to like beartype, any workarounds?

**Comment by bionicles** [comment] 2024-06-23 15:55
here's what i tried: 
```
# ....................{ BIG BEAR                        }....................
# Warn about type hint violations in *OTHER* packages outside your control;
# only raise exceptions from violations in your package under your control.
# Again, at the very top of your "{your_package}.__init__" submodule:
from beartype import BeartypeConf  # <-- this isn't your fault
from beartype import BeartypeViolationVerbosity
from beartype.claw import (
    # beartype_all,
    beartype_this_package,
)  # <-- you didn't sign up for this

beartype_conf = BeartypeConf(
    violation_verbosity=BeartypeViolationVerbosity.MINIMAL,
)
beartype_this_package(conf=beartype_conf)  # <-- raise exceptions in your code
# beartype_all(
#     conf=BeartypeConf(violation_type=UserWarning)
# )  # <-- emit warnings from other code
```

**Comment by leycec** [comment] 2024-06-25 05:46
*...heh.* Anger, huh? I was wondering when I was going to start receiving anger-filled invective. Anything that receives attention eventually receives anger-filled invective. It's a law of the Internet probably called McMurdo's Law of Anger Attraction. With @beartype on the cusp of garnering widespread attention beyond the cozy confines of the ML (machine learning) community, it was *sorta* inevitable that this day would dawn. And... here it is. The angry day dawned. And it's angry! :angry: <sup><--- *angry guy angers around*</sup>

I once used to be an angry person, too. I pretty much lost my 30's – an entire *decade* – to anger-filled invective. Sadly, I was anger personified in the flesh. It was a disastrous look, a debacle of a decade, and a time I now reflect on with an upwelling sense of loss and sadness. I'm all too familiar with the emotion. As a full-blown autist with [alexithymia](https://en.wikipedia.org/wiki/Alexithymia), anger was pretty much the only human emotion I ever genuinely felt. All of which is to say...

## @beartype: It Prolly Ain't for You

Like, seriously. @beartype behaviour and documentation upsets you. You're *not* necessarily wrong, of course. @beartype is a flawed vessel, because I am a flawed human. @beartype is human stuff. No amount of issue resolutions on my part can possibly change, rectify, or mollify the negative emotions on display here. Anger tends to be resilient to change. Anger is *fixed* in place.

It kinda just sounds like @beartype isn't for you. @beartype isn't here to generate anger, enhance frustration, or make the world an even worse place than the world already is. If this is happening when you use @beartype, then @beartype has failed your use case. The best (and really only) remedy is to drop @beartype from your app stack. That's what I'd do, anyway.

I have zero tolerance for software that upsets me. There's just not enough time in a single lifetime to squander on upsetting things. You're probably not *too* different in that respect, right? This world is upsetting enough already. It might be time for you to just "pump and dump" @beartype. That said...

## @beartype: It Isn't *Entirely* to Blame Here

The traceback you exhibited above is a sterling example. Anger and confusion have intersected here to obfuscate the underlying issue. A good third of that traceback derives from `pytest` itself. Another 10% or so derives from standard `importlib` machinery. Neither of those things are @beartype. Right? @beartype can't do anything about either `pytest` or standard `importlib` machinery. Those things do themselves outside @beartype's purview. They're beyond us. Which is probably a good thing. You wouldn't trust @beartype to start mucking around with `pytest` or standard `importlib` machinery, would you? I wouldn't. I wouldn't trust @beartype to monkey-patch *anything*. And I wrote this shambolic monster.

As for the remaining 60% or so your traceback that *does* derive from @beartype, that's actually a good thing. Wait! Hear me out, please. I am about to say something crazy. Thankfully, crazy people are interesting. Everybody likes a show. Because...

**I need tracebacks to debug @beartype.** Without tracebacks, resolving issues is infeasible. That would be far worse than users confronting upsetting tracebacks – which should *never* happen, anyway. We're talking extreme outlier events here. Why? Because...

## @beartype: It Blew Up, but You Didn't Know It

**Something blew up deep inside @beartype here.** Clearly, you hit something resembling a @beartype bug here.

@beartype only raises a traceback when something goes catastrophically unexpected. Because @beartype raised a traceback, something (*...wait for it*) went catastrophically unexpected. Unfortunately, you omitted the exception message. I can't say with any confidence what *exactly* went wrong here. But I surmise it has something to do with a class annotated by a type hint unsupported by @beartype. But @beartype supports pretty much *all* type hints. So... I'm confused and can't do very much to assist you. It is sad. Weep, sobbing emoji face! :sob: 

@beartype intentionally omits tracebacks when type-checking violations occur. That covers **99.99%** of the exceptions raised by @beartype. This means that **99.99% of @beartype users never see any tracebacks containing @beartype internals**: e.g.,

```python
>>> from beartype import beartype
>>> @beartype
... def fun_func(bad_arg: str) -> None: pass
>>> fun_func(b'Suck eggs, fun func!')
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    fun_func(b'Suck eggs, fun func!')
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(__main__.fun_func) at 0x7f453a42ad40>", line 29, in fun_func
beartype.roar.BeartypeCallHintParamViolation: Function __main__.fun_func() parameter
bad_arg=b'Suck eggs, fun func!' violates type hint <class 'str'>, as bytes
b'Suck eggs, fun func!' not instance of str.
```

See? No @beartype internals, right? That's intentional. Nobody wants @beartype internals in type-checking violations. So @beartype works *surprisingly* hard to omit @beartype internals from type-checking violations. Technically, it would be possible to also omit @beartype internals from decoration-time exceptions like the kind of exception you hit above. Pragmatically, doing so would be disastrous. If I omitted @beartype internals from decoration-time exceptions, then I'd have no means of resolving *any* issues whatsoever. That would be like *Godzilla on Mothra* all over again.

Nobody is supposed to see exceptions like the exception you are seeing. Whenever you see an exception like that from *any* package, your thought process should *usually* go something like this:

> "Something blew up. This is bad. Oh, Gods. I heard shattering glass. And... *was that gun shots?* And I'm pretty sure I heard a small baby screaming. I don't feel angry. I feel sad and scared! Explosions are scary! I'd better report what I saw to the authorities. Oddly, that happens to be this autistic guy @leycec in this case. Whatever! The explosions, the shattering glass, the gun shots, and the small baby screaming is all that guy's problem now. I feel better. That's what matters."

In other words, @beartype users are supposed to:

* **(A)** Be surprised by super-long tracebacks like the one you hit *and*...
* **(B)** Submit them as issues to this issue tracker.

Everything's actually working as intended from @beartype's perspective. @beartype wasn't trying to make you feel wrathful anger and a desire to bludgeon @beartype into oblivion. By presenting you with an uncomfortably long traceback dredged up like a Balrog from the mines of Moria, @beartype was trying to convince you that the sky is now falling, that the five riders of the QA Apocalypse are now cavorting through your codebase, and that you should probably tell somebody about that as soon as possible so that they can fix that for you and stave off the QA Apocalypse. Right? QA Apocalypse == *bad*.

But you had the opposite reaction. You didn't quite grok the enormity of @beartype was trying to tell you. It probably would have helped if @beartype could have screamed. In code, only the AI can hear @beartype scream. You mistakenly assumed that everything was normal and that @beartype was just doing something dumb. This assumption then led you to anger.

But the assumption itself was false. Everything was very much *not* normal. @beartype was trying to doing something smart, but failing. @beartype was trying to get your attention. @beartype was wildly flapping its wings around like a headless chicken in a TikTok rodeo contest gone horribly awry. Ergo, the anger itself was predicate on a false assumption. In other words...

## Anger: What Is Good For?

*Absolutely nuthin'.* Anger isn't a tool. North American culture got that tragically wrong. Anger is the small death that feeds every greater demise. This is the lesson eternal:

```
Dev bros don't let dev bros anger.
Not even once.
       – some bald autistic guy on GitHub, probably
```

**Comment by bionicles** [comment] 2024-06-25 11:01
Observation: There is a long comment with what seems like an assumption this issue was created in anger.

Feeling: This makes me feel unheard, I wasn't angry, just felt like I had wasted my time, and the comment makes me feel like my time is being disrespected.

Need: I, like many developers, value being able to provide honest negative feedback about developer experience without this being assumed to be angry or hostile. 

Request: If this kind of experience ought to yield a structured bug report, then could it be possible for beartype to output the verbose tracebacks to an error log file and provide guidance about the best way to upload that error log file to a github issue? I'd be glad to share the logs but they literally took up my entire terminal history, impossible to copy them all here, not to mention it's a private repo, how do we balance these objectives productively? 

I sincerely apologize if I made you feel like I don't appreciate your work on your project. It just didn't work the way I tried to work with it. That doesn't mean it's a bad project or is broken, just means, maybe it's a sign to guide folks more gradually into the land of beartype (like instead of guidance to enable beartype broadly for whole projects, docs could guide us to enable for one single tdd red/green/refactor cycle), and proactively minimize crash errors into an artifact to be conveyed to this issue tracker.

For a nugget of technical detail, I was trying to use the python 3.12 type to alias parametric generics and access the methods at runtime through the alias, which could explain why it crashed .. python type alias types are not Deref like every other type system I've worked with, so they don't resolve methods of the aliased type. I wound up needing to make a lot of changes, so you're right, it was a sign I was doing something wrong, I just got overwhelmed by the huge wall of tracebacks, that's all. 

For every person like me who experiences this and posts here, there are almost surely others who are use it and get discouraged and stop using it without raising any issue at all. So I hope you'll realize that I was putting myself out there to help improve your project with honest feedback, and not aiming to put you down, though I admit I could have been more tactful and diplomatic.

Keep up your work, type level python is crucial for correctness of many of the most critical pieces of software around. 

[1] https://en.wikipedia.org/wiki/Principle_of_charity

**Comment by leycec** [comment] 2024-06-27 05:01
**Aaaaaand...** you're still angry. It is what it is. I call a spade a spade. I know anger. I'm sadly familiar.  There's no shame in anger, either. It's a stock human emotion. It's *natural* to feel anger. This is anger:

> that's patronizing BS

This is anger, too:

> "SKILL ISSUE"

This is anger as well:

> not helpful

This is anger yet again:

> dealbreaker

This is anger all over:

> useless details

And that was just your first comment. I'm not even touching that *third* comment. Casually throwing around slurs like "patronizing BS" to Internet strangers volunteering free work for you is textbook anger, toxic abusiveness, and injudicious in the extreme. I don't do that to Internet strangers. I'd appreciate the same consideration in kind.

If you'd rather not acknowledge the self-obvious, well... that's cool, I guess. You're in your own meat suit, of course. You know your emotions best. I'm certainly not here to belabour the subjective point. Neither are you, right? We've all got some spicy deving to dev. Code ain't gonna code itself.

So let's get down to brass tacks. I'm more than happy to ignore the anger, the passive-aggressiveness, and whatever else is going on here. Personality conflict, maybe? Seems plausible. Autism sure ain't for everybody. Ultimately, I'm just here to fix bugs. QA is @beartype's bread and butter. However, to belabour the only point that matters...

## I Need an Example to Fix Bugs

**That's it.** That's all I need here. That's all *any* package maintainer needs. Please feed me a **minimal reproducible example (MRE)**. Something reasonably short and to the point that exhibits the issue you're seeing. Given that, I'll gratefully resolve whatever issue this is for you and everybody else.

A **traceback** would also be useful – a *full* unredacted traceback complete with exception message. Screenshots are cool, I guess, but not nearly as useful as a working example and a full traceback.

Sound good? Sounds good. It's a good deal. Everybody wins. Winning is good. Let's win. :muscle: <sup>*big muscles mean winning is happening*</sup>

## Exception Tracebacks are Good – Not Bad

Until then, there's not much meaningful I can do with this. Aside from whatever bug is happening here, @beartype is otherwise working as intended.

As [suggested above](https://github.com/beartype/beartype/issues/398#issuecomment-2188028097), I need tracebacks to resolve bugs. Without tracebacks, bugs cannot be resolved. "Minimizing" tracebacks away is a non-starter. No one should want to do that *ever* for *any* open-source Python package – including @beartype. No one should even see tracebacks with @beartype internals in them in the first place. If you see a traceback with @beartype internals, that's a bug that I need reported to me.

So, this feature request doesn't particularly make sense. With apologies, let's quietly close this for sanity. I *hate* closing issues unresolved. I *hate* arguments, too. Since both of those things are now happening, neither of us had a good time with this one.

My emoji face sighs in spent exhaustion. :face_exhaling:

**Closed by leycec** 2024-06-27 05:01 UTC

**Comment by bionicles** [comment] 2024-06-27 11:00
I see you're labeling my emotions.

That makes me feel you're not attending to my attempt to be more diplomatic. To be clear, in the first message, I was just in disbelief that an infinite wall of tracebacks is an acceptable dev experience. It was more of a diss / insult, than being angry. Need me to calmly read the text on youtube or something so you can catch my tonality? I was mocking you, not mad at you.

To provide a complete traceback, I need to be able to select it, but I can't because it fills the whole terminal history buffer.

Could it be possible pipe the entire verbose tracebacks into a text file to upload, and then print the user code to the terminal? Issue persists because developers will read the docs, enable beartype broadly, hit a wall of tracebacks, and disable beartype. Thank you for your understanding.

**Comment by bionicles** [comment] 2024-06-27 11:11
anyway, my first message was mean out of line so i don't blame you for not wanting to help, 

helpful book for folks in our situation, if i'd written my first message according to this book, then it would not have been mean https://www.nonviolentcommunication.com/learn-nonviolent-communication/4-part-nvc/
