### ISSUE TITLE
[Feature Request] Resuscitate `typing.TypeGuard[T]` type narrowing on `beartype.door.is_bearable()`

### ISSUE THREAD

**Issue by alexander-c-b** [beartype/beartype#255] opened 2023-07-17 04:10 UTC
### Synopsys

`beartype.door.is_bearable` cannot be used for type narrowing with `mypy` or `pyright` as described in the documentation, due to an incorrect type annotation.

### To Reproduce

Both `mypy` and `pyright` show type errors with this example from [the Beartype documentation](https://beartype.readthedocs.io/en/latest/faq/#with-type-narrowing):

```python
from beartype.door import is_bearable

def narrow_types_like_a_boss_with_beartype(lst: list[int | str]):
    if is_bearable(lst, list[int]):
        munch_on_list_of_integers(lst)
    elif is_bearable(lst, list[str]):
        munch_on_list_of_strings(lst)

def munch_on_list_of_strings(lst: list[str]): ...
def munch_on_list_of_integers(lst: list[int]): ...
```

Result from `mypy`:

```sh
$ mypy ./bug.py  
bug.py:5: error: Argument 1 to "munch_on_list_of_integers" has incompatible type "Type[List[Any]]"; expected "List[int]"  [arg-type]
bug.py:7: error: Argument 1 to "munch_on_list_of_strings" has incompatible type "Type[List[Any]]"; expected "List[str]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

Result from `pyright`:

```sh
$ pyright ./bug.py 
[elided]/bug.py
  [elided]/bug.py:5:35 - error: Argument of type "type[list[int]]" cannot be assigned to parameter "lst" of type "list[int]" in function "munch_on_list_of_integers"
    "type[type]" is incompatible with "type[list[int]]" (reportGeneralTypeIssues)
 [elided]/bug.py:7:34 - error: Argument of type "type[list[str]]" cannot be assigned to parameter "lst" of type "list[str]" in function "munch_on_list_of_strings"
    "type[type]" is incompatible with "type[list[str]]" (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations
```

### Expected behavior

`mypy` and `pyright` should show no errors when type-checking the code.

### Extra notes

The type signature of `is_bearable` is as follows from the source code:

```python
def is_bearable(
    obj: object,
    hint: T,
    *,
    conf: BeartypeConf = BEARTYPE_CONF_DEFAULT,
) -> TypeGuard[T]:
   ...
```

For example, if the user calls `is_bearable(some_variable, int)`, then `T` is bound as `type[int]` instead of `int`, since `T` has to be the type of whatever argument was passed in (which was `int`).  Thus, static type checkers now believe that `some_variable` has the type `type[int]` instead of the correct `int`.

This can can be fixed by a simple change to the type signature:

```python
def is_bearable(
    obj: object,
    hint: type[T],
    *,
    conf: BeartypeConf = BEARTYPE_CONF_DEFAULT,
) -> TypeGuard[T]:
   ...
```

Now, when `is_bearable(some_variable, int)` is called, `T` will be assigned to `int`, and so `some_variable` will be correctly identified as having type `int` instead of `type[int]`.

Unfortunately, this change seems to break type checking on other parts of the code (namely `beartype.door._cls.super.TypeHint`).  I'm not sure how these other type hints should be corrected, which is why I submitted an issue instead of a PR.  If anyone reviewing this issue has any guidance on how any other type annotations should be modified, I would be happy to attempt a PR again to fix this issue.

**Comment by leycec** [comment] 2023-07-17 19:03
**Gah!** Thanks so much for the heads up, @alexander-c-b. I sadly concur that `beartype.door.is_bearable()` and `beartype.door.TypeHint.is_bearable()` appear busted... *which is wierd,* because I'm pretty sure this used to work.

Technically, I haven't tested this in over a year; it's non-trivial to implement an integration test that exercises this functionality in our `pytest` test suite. So, I didn't. Laziness won again and we all suffer for it.

Pragmatically, I manually tested this over a year ago with a similar approach to your *awesome* minimal reproducible example (MRE); everything worked back then, I think. Alternately, I may have spontaneously hallucinated everything due to heat stroke induced by Canada now being on fire constantly. This is the dark possibility that no one wants to ponder.

## `T`: The Cause of All Our Problems (And Now Yours, Too)

So... **I am stumped.** The crux of this issue appears to be that `typing.TypeVar` is implicitly bound to the *type* of the passed type hint rather than the actual type hint itself. But we can't simply replace that by `type[T]`. Most type hints either:

* Are *not* actually types.
* *Are* actually types but those types are not actually meaningful in any sense.

If all of this is true, then both [PEP 647 – User-Defined Type Guards](https://peps.python.org/pep-0647) and `typing.TypeGuard[...]` are useless for the most useful real-world use cases: general-purpose runtime type-checkers like @beartype and `typeguard` that type-check literally everything. You'd only be able to define special-purpose runtime type-checkers isolated to specific type hints like `def is_list_of_integers(obj: Any) -> TypeGuard[list[int]]`.

It kinda seems like @beartype has no means whatsoever of typing this constraint. We should immediately comment out that FAQ entry in the hopes that someone [read: *tyrannical overlord AI*] will save us from our sins in the far distant future. That FAQ entry is currently a blatant lie, which isn't great. I sigh! I sigh loudly, everybody! :face_exhaling:

**Comment by leycec** [comment] 2023-07-18 03:50
@justinchuby, @rsokl: **I summon thee.** You were both so instrumental in pushing @beartype to support [PEP 647 – User-Defined Type Guards](https://peps.python.org/pep-0647) (i.e., `typing.TypeGuard[...]`) in our `beartype.door.is_bearable()` function and corresponding `beartype.door.TypeHint.is_bearable()` method. You deserve to know the horrible truth...

Something horrible happened! I'm unsure who's to blame. It's probably me. Regardless, @beartype's PEP 647 support now appears to be broken. We don't control static type-checkers, so we have little say in the manner. Still, I have many questions and no answers:

* **Did this *ever* work?** I'm pretty sure it did a year or two ago. Of course, I tested this at that time. Of course... :sweat_smile: 
* **Is this mypy and `pyright`'s fault?** Did the static type-checking community quietly agree to break something (e.g., `typing.TypeVar` support) that used to make this work?

Until answers arrive, I shall continue doing nothing. I'm good at that.

**Comment by A5rocks** [comment] 2023-07-18 08:24
> Are not actually types. They're bizarre objects whose types are useless private classes internal to the typing module (e.g., typing._SpecialForm). Don't ask. Nobody is supposed to know about any of that special madness.

pyright accepts `type[T]` in the way that shouldn't really work. Mypy used to, but as you've noted that's just... wrong. There's an [open issue request](https://github.com/python/mypy/issues/9773) and a PEP that's supposedly being written, but probably needs someone to push it. As far as I know, there's no good solution to this, leading to stuff like `cattrs` (which finds itself in a similar situation) just giving up and doing something that doesn't work:

https://github.com/python-attrs/cattrs/blob/5f5c11627a7f67a23d6212bc7df9f96243c62dc5/src/cattrs/converters.py#L332-L334

**Comment by leycec** [comment] 2023-07-19 05:51
Thanks so much for the heads up, @A5rocks. At least we have all learned that PEP 647 (i.e., `typing.TypeGuard`) is useless for almost everything it intended to do. Ignorance is truly bliss and I want to go back there. 

This is surely further confirmation that we're on the bad timeline and rapidly heading to a worst-case scenario – which includes me whimpering alone in a leaky kayak in the middle of Lake Ontario in late November while the impenetrable fog from which strange midnight denizens murmur and roar encroaches. Something that gibbers and froths in the darkness snatches the paddle from my frigid fingers. Also, I'm all out of bubblegum.

**Note to self:** let's quietly remove that FAQ entry, our `TypeGuard[T]` return type hints on `is_bearable()` and `TypeHint.is_bearable()`, and pretend this grim evening never happened. I'm cool with that.

**Comment by skeggse** [comment] 2023-07-24 22:59
Well, glad I stumbled upon this thread! Is our intention then to support this if/when there's a PEP that does what we want it to do?

**Comment by leycec** [comment] 2023-07-25 19:40
**Yuppers.** That's the 20-year plan exactly. Until then, **commit 2ae007b** did the dirty deed done dirt-cheap. As prophesied:

* I've quietly removed that FAQ entry.
* I've quietly removed our `TypeGuard[T]` return type hints on `is_bearable()` and `TypeHint.is_bearable()`.
* I'm now pretending this grim evening never happened.

I'm still cool with that. If and when static type-checkers somehow support our use case, someone please reopen this issue. The bear cat hangs its soggy and shaggy head in sadness. :crying_cat_face:

**Comment by JWCS** [comment] 2024-02-20 17:30
from 166: RIP. But, when I was then inspired to look through mypy issues for the waiting blocks, it kinda seemed like this was implemented? But those PRs / closed issues would've been before beartype 0.12.0, so I'm not sure if there's any open issues there on this topic?
Does the typeguard author & maestro @erictraut have deeper wisdom on what's missing either in mypy, or out of the pep 647 spec?
(Note: when I was looking to remember how well typeguard was supported by beartype, the only docs I could easily find were the BigData/pep section, stating compliance since 0.13.0, which then I found the release notes for. In lieu, it seems this issue + 166 is the source of truth.)

**Comment by leycec** [comment] 2024-02-21 07:29
*...huh.* You totally and probably might be right, @JWCS. A trivial CLI-based test suggests that mypy might have joyfully repaired itself while nobody was looking. As a test driver, we define a fake `is_bearable()` tester with a similar signature to the real `is_bearable()` tester:

```python
from typing import TypeGuard, TypeVar
T = TypeVar('T')

def is_bearable(obj: object, hint: T) -> TypeGuard[T]:
    return True

is_bearable(['yum'], list[str])
```

...for which mypy reports:

```bash
$ mypy test_driver.py
Success: no issues found in 1 source file
```

I'm still concerned about `pyright` and Pyre and all those *other* guys – but lack of compliance with mypy would arguably constitute an issue in those *other* guys, which certainly isn't our responsibility.

Let's reopen this for great glory of typing community! :partying_face:

**Comment by leycec** [comment] 2024-02-21 07:36
**Oh, bother.** I expanded my test driver to incorporate the sensible unit test originally devised by @alexander-c-b above and... *yeah.* From the little that I can tell, mypy remains busted in the exact same way:

```python
# In "test_driver.py":
from typing import TypeGuard, TypeVar
T = TypeVar('T')

def is_bearable(obj: object, hint: T) -> TypeGuard[T]:
    return True

def narrow_types_like_a_boss_with_beartype(lst: list[int | str]):
    if is_bearable(lst, list[int]):
        munch_on_list_of_integers(lst)
    elif is_bearable(lst, list[str]):
        munch_on_list_of_strings(lst)

def munch_on_list_of_strings(lst: list[str]): ...
def munch_on_list_of_integers(lst: list[int]): ...
```

```bash
$ mypy test_driver.py     
test_driver.py:11: error: Argument 1 to "munch_on_list_of_integers" has incompatible type "type[list[Any]]"; expected "list[int]"  [arg-type]
test_driver.py:13: error: Argument 1 to "munch_on_list_of_strings" has incompatible type "type[list[Any]]"; expected "list[str]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

*...lol.* mypy, y u still h8 @beartype in 2024? I sigh. :face_exhaling:

**Comment by erictraut** [comment] 2024-02-21 08:00
@leycec, I think you have a bug in your type guard function. The annotation for the `hint` parameter should be `type[T]`, not `T`.

> ...lack of compliance with mypy would arguably constitute an issue in those other guys...

The [Python type specification](https://typing.readthedocs.io/en/latest/spec/index.html) is the source of truth for type checker compliance, not mypy. While mypy is mostly compliant with the spec, it is not fully compliant. The typing community has been working on a set of type checker conformance tests, and you can view the latest results [here](https://htmlpreview.github.io/?https://github.com/python/typing/blob/main/conformance/results/results.html).

**Comment by leycec** [comment] 2024-02-22 09:06
**Nopers,** sadly. But I like the way you think. You're trying! That's more than can be said for mypy. `T` is defly right here. Why? Because *type hints are not types* – not in the general case, anyway. They're arbitrary objects. Yes, it's all true. Some type hints actually are types, of course. But most aren't.

Let's buff up the horrifying test driver above with even more hideous logic to explicate the edge cases:

```python
# In "test_driver.py":
from typing import Annotated, TypeGuard, TypeVar
T = TypeVar('T')

def is_bearable(obj: object, hint: T) -> TypeGuard[T]:
    return True

def narrow_types_like_a_boss_with_beartype(lst: list[int | str]):
    if is_bearable(lst, list[int]):
        munch_on_list_of_integers(lst)
    elif is_bearable(lst, list[str]):
        munch_on_list_of_strings(lst)
    elif is_bearable(lst, Annotated[str, 'ohgods... ohgods!']):  # <-- horrible new stuff
        print('This sucks, bro.')                                # <-- more bad new stuff

def munch_on_list_of_strings(lst: list[str]): ...
def munch_on_list_of_integers(lst: list[int]): ...
```

**kk.** So, that continues to emit the expected mypy "errors" above. But if we erroneously refactor `hint: T` to instead read `hint: type[T]`, then mypy vomits up this new and unexpected "error":

```python
test_driver.py:14: error: Argument 2 to "is_bearable" has incompatible type "object"; expected "type[Never]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

The `expected "type[Never]"` substring is particularly juicy. Like, what are you even talking about, mypy? What's `Never`? Never seen a `Never`. Can't instantiate a `Never`. Can't introspect a `Never`. That's not a builtin type. That's some weird mypy-specific thing nobody's never heard of.

Honestly, this whole thing hurts my face. I exhale. :face_exhaling:

**Comment by asford** [comment] 2024-03-22 18:18
As a follow-up with some more digging, the emergent `Annotation` behavior has already been discussed in various forums:

The typing clarification that restricts this use of Annotated in value expressions:
https://github.com/python/typing-council/issues/18
"[...] reject the use of Annotated when assigned to type[T]. The latest version of pyright (1.1.350) does likewise, making it consistent with mypy and pyre and the proposed spec clarification."

The current mypy-tracking/discussion issue for `TypeForm` is at: https://github.com/python/mypy/issues/9773
which is now ♨️ heating up ♨️ toward a PEP-proposal.

**Comment by leycec** [comment] 2024-03-23 07:59
> ## Context, the Corporeal and Platonic Realms

*You have my full attention.*

> `is_bearable` is a runtime-static hybrid type checking monstrosity,

Some prefer the term "utopian dream unicorn." Others, "monstrosity." I'm currently 50-50 on either.

> which explicitly flexes its ability to root through runtime information to resolve otherwise-impossible type verification tasks.

This Pythonista type-checks. When the impossible goes possible, you know your app stack is currently being crushed under the ponderous weight of @beartype.

> It uses (in the eyes of some, **abuses**)

![](https://media1.tenor.com/m/15TYaz8lE0EAAAAC/idiot-fight.gif)

> That the bear, when grubbily reaching its paw across this gap, should error & fumble should be understandable to us all.

H-h-ow dare you! Yes, it's true. The bear is grubby. It's paw, even grubbier. But nobody errors and fumbles like @beartype! Wait. Let's rollback. @beartype is probably infallable. Since this is probably true, all *apparent* errors and fumbles that may or may not have destroyed your production workloads are *apparently* somebody else's fault.

> However, `is_bearable` is willfully unconstrained and will gamely and **unsafely**

![](https://media1.tenor.com/m/iIvYHZv2wp8AAAAC/baby-doll.gif)

> the world is better than you imagine, and sometimes the error is our own. 🌈🐻😄

I imagined a miraculous world. Then I moved to Canada. Now, I merely imagine five cats stacked on my lap as I coax the last life-giving nugget of hot cocoa out an unwashed mug in front of a fireplace I haven't moved from in seven weeks.

The neckbeard is real.

> These two systems, so alike in selfless aspiration but so very different in kind, can meet in their common ground... a rare ray of hope in today's world, which is often so unbearable grim and divided?

**My Gods.** So, it is true. It's all true. The diabolic conspiracy against truthful type-checking ends in a bittersweet hug as @beartype tearfully embraces the static type-checkers it has simultaneously loathed and yet been painfully jealous of its entire existence.

@beartype: *Was it wrong to be so jelly?*

> This captures of subset of `is_bearable` checking behavior where it functions as a compliant `TypeGuard`, while appropriately falling back to a non-false-positive overload in cases where it extends beyond `TypeGuard` semantics.

**Incroyable!** I don't even know what that means, but apparently it's an expression of defiant ebullience in the face of shared hardships!

Seriously, though. I have no idea how you solved the decades-long Hellraiser Cube Puzzle Box that is @beartype **+** PEP 647 integration. I don't even know if both of us are human anymore. Your cuboidal avatar leaves me with nagging doubts. Surely, one of us has now transcended the fragile bounds of the mortal coil and now resides in an infinite hyperplane of jiggling QA entities all named Bob.

Wait. I was supposed to be serious there. I even said "Seriously, though." That signifies seriousness is about to begin. But... *I couldn't do it.* I couldn't stay serious even long to say...

**Let's reopen this issue immediately and do this!** Buh-yah!

![](https://media1.tenor.com/m/WKE8CAQ2JqoAAAAC/allosaurus-tyrannosaurus.gif)
<sup>Left: *@beartype.* Right: *PEP 647.*</sup>

**Comment by leycec** [comment] 2024-03-28 07:17
*...heh.* @leycec isn't funny anymore, huh? Fair. Fair enough. My wife and cats agree, as the raking claw marks on my back and inner thighs attest. Folks, do *not* let those cats on your lap!

> *...uhm...*

Let's pretend the prior two sentences didn't happen. What I *meant* to say is... **this feature request has now been resolved by 874776af77f27090!** Specifically, this commit:

* Restores @beartype support for PEP 647, entirely thanks to a [mammoth dissertation-length dissection](https://github.com/beartype/beartype/issues/255#issuecomment-2015555878) of the intersection <sup>*...oh gods what does any of this mean anymore*</sup> of runtime and static type-checking vis-a-vis the procedural statement-level hybrid runtime-static type-checker `beartype.door.is_bearable()`, the PEP 484-compliant `@typing.overload` decorator, *and* the PEP 647-compliant `typing.TypeGuard[T]` type hint – all courtesy Python's unassailable `typing` genius @asford (Alex Ford). A prefatory comment in the @beartype codebase now glibly reads:

  ```python
  # Note that this PEP 484- and 647-compliant API is entirely the brain child of
  # @asford (Alex Ford). If this breaks, redirect all ~~vengeance~~ enquiries to:
  #     https://github.com/asford
  ```

* Restores our [previously disabled FAQ entry documenting @beartype support for PEP 647](https://beartype.readthedocs.io/en/latest/faq/#with-type-narrowing).

Sadly:

* This does *not* extend to the comparable object-oriented `beartype.door.TypeHint.is_bearable()` method – which continues to *not* perform type narrowing. Due to deficiencies in @leycec's wobbly brain, only the procedural `beartype.door.is_bearable()` function currently performs type narrowing.
* This may *not* extend to pyright. Although mypy appears to fully support this API, pyright appears to raise fatal errors that make *no* sense and suggest pyright to have an equally wobbly brain:

  ```
  /home/leycec/py/beartype/beartype/door/_doorcheck.py
    /home/leycec/py/beartype/beartype/door/_doorcheck.py:209:5 - error: Overloaded implementation is not consistent with signature of overload 1
      Function return type "TypeGuard[T@is_bearable]" is incompatible with type "bool"
        "TypeGuard[T@is_bearable]" is incompatible with "bool" (reportInconsistentOverload)
    /home/leycec/py/beartype/beartype/door/_doorcheck.py:209:5 - error: Overloaded implementation is not consistent with signature of overload 2
      Function return type "TypeGuard[T@is_bearable]" is incompatible with type "bool"
        "TypeGuard[T@is_bearable]" is incompatible with "bool" (reportInconsistentOverload)
  2 errors, 0 warnings, 0 informations
  ```

What's "funny" about that is that:

* *All* `TypeGuard[...]` type hints (including `TypeGuard[T@is_bearable]`, whatever that even is) reduce to and are thus compatible by definition with the standard `bool` type.
* PEP 647 claims that the reference implementation of PEP 647 is (*...waitforit*) pyright:

      The Pyright type checker supports the behavior described in this PEP.

Guess it doesn't, huh? We cry wet crocodile tears for OO and pyright. :crocodile: :cry: 

Thanks again for playing along in the @Beartype playpen of manifest darkness, everybody. Special thanks to @asford for his deep dive into PEP 647 semantics that I still only vaguely understand and shamefully failed to apply to the `beartype.door.TypeHint.is_bearable()` method.

This resolution is for you, @asford. May 2024 bless you with many untold delights.

**Closed by leycec** 2024-03-28 07:17 UTC

**Comment by TeamSpen210** [comment] 2024-03-28 09:12
In regards to Pyright's error there, it was correct as originally specified. [TypeGuard actually wasn't compatible with bool](https://discuss.python.org/t/compatibility-between-typeguard-and-bool/46364) when the PEP was originally defined. Only recently this was noticed, and [changed by the Typing Council](https://github.com/python/typing-council/issues/20). Maybe Pyright hasn't handled the change in this specific case? For `T@is_bearable`, that's a Pyright-specific notation used to indicate what scope the typevar applies to, hopefully making messages clearer if there's multiple vars with the same name involved.

**Comment by asford** [comment] 2024-03-28 15:26
> I imagined a miraculous world. Then I moved to Canada. Now, I merely imagine five cats stacked on my lap as I coax the last life-giving nugget of hot cocoa out of an unwashed mug in front of a fireplace I haven't moved from in seven weeks.

My friend... I too have been to the north and felt the cutting chill that rides on on these frozen winds. 
May your mug always carry the nourishing nugget; perhaps loosed with a faintest splash of your preferred potable as the sun rises above the horizon every spring after its long winter repose.

> all courtesy Python's unassailable typing genius ...

You unjustly flatter me, for I'm no typing genius; imagine me only as a mate locked on this Pequod.
Sailing the oft-stormy waters where the sea and sky of typing meet, occasionally gifted with moments of high perception?
Merely a man, a loyal Starbuck? Or perhaps, as you note, more... a man with madness maddened.

> https://github.com/beartype/beartype/commit/874776af77f27090e0594db3954d94cb805f0054

To awake this morning and find this on my desk was more invigorating that even the darkest brew steaming in my cup.
Beartype's wind now fills my sails 🐻 💨  ⛵
Its claws the iron rails on which we set the serpentine scrivenings of the so many scientists that are our crew.

🥂 ☕ 🌞 complements to you... to beartype... to the typing council...  and to the infinite hyperplane (hypercube?) of QA that is Bob.

**Comment by leycec** [comment] 2024-03-29 07:08
@TeamSpen210: **Oh, Gods.** How do you know everything? It's fascinating yet horrifying that `TypeGuard` and `bool` were intentionally incommensurate in the original PEP. I mean, I read that too. Surprising, huh? You don't believe me. I know you! But it's true. I actually read the PEP – but I didn't believe what I was reading, because it made no sense. I ignored what I was reading.

Thankfully, somebody finally agreed with @leycec. I feel so vindicated in my life. :triumph: 

> perhaps loosed with a faintest splash of your **preferred potable**

@asford: Let's admit we're talking about a liquid slurry of cannabis resins. `#justcanadianthings`

> You unjustly flatter me, for I'm no typing genius; imagine me only as a mate locked on this Pequod.

**...oh.** Oh, American patriotism strikes quick in my pasty bosom. Did you *really* just slyly name-drop Herman Melville? Verily, I do believe that happened. I saw it! You exhibited your profound intellect for all to see as if it was no mean feat again! But you can't fool anyone anymore, @asford. We know and reluctantly accept that you're smarter than us. Now anyone who inspects the @beartype codebase will know this cutting yet undeniable truth. Sometimes, it is more painful to deny than to accept.

I may never be a poet in this life. But at least I knew a poet in this life. I quoth this liquid slurry of cannabis resins for you before passing out and drooling all over myself. :beers:
