### ISSUE TITLE
[Bug] `is_bearable({"1": "2"}, dict[int, int])` is `True`

### ISSUE THREAD

**Issue by wesselb** [beartype/beartype#246] opened 2023-06-26 19:02 UTC
Hey @leycec!

I hope you're doing well. :)

It appears that `is_bearable` ignores the type parameters of `dict` where `TypeHint` doesn't:

```python
In [1]: from beartype.door import is_bearable

In [2]: is_bearable({"1": "2"}, dict[int, int])  # :(
Out[2]: True
```

```python
In [1]: from beartype.door import TypeHint

In [2]: TypeHint(dict[int, int]) <= TypeHint(dict[str, str])   # :)
Out[2]: False

In [3]: TypeHint(dict[int, int]) <= TypeHint(dict)  # :)
Out[3]: True
```

Could something be going wrong inside `is_bearable`? This is on the latest version of `beartype` on both Python 3.9 and Python 3.11.

(We came across this problem [here](https://github.com/beartype/plum/issues/88).)

**Comment by leycec** [comment] 2023-06-27 05:57
**@wesselb!!!** The prodigal Dutch bear bro returns. :partying_face: 

Yes, sadly; the depressing rumours of our ineptitude are all too true. @beartype itself currently only shallowly type-checks `hash`-based containers like `set` and `dict` collections. Please see also the [**BigData™** page of @beartype's official yet bedraggled documentation](https://beartype.readthedocs.io/en/latest/pep), which voluminously documents exactly which type hints @beartype supports and (more importantly) exactly *how* @beartype does so (e.g., deeply or just shallowly). In this case, it is shallowly. <sup>*sigh*</sup>

Admittedly, this is bad. Thankfully, typing maestro @langfield at open issue #167 has repeatedly and justifiably shamed me into acknowledging that this is bad and that I should rectify this before earning any further demerit points on my GitHub driver's license. Since this issue is a duplicate of #167, let's just quietly close this duplicate and pretend I did something meaningful. Oh, and...

**My plan is this.** First, [I finish import hooks](https://github.com/beartype/beartype/issues/43). Then, I do this. That's the plan. It is a plan so foolproof that nothing can possibly blow up in our faces.

Thanks as always for being so awesome, @wesselb. I hope you and your loved ones are having an excellent summer sweltering with sweaty beach and pool time. *Cannonbaaaaaaaaaaaaall!*

**Closed by leycec** 2023-06-27 05:57 UTC

**Comment by wesselb** [comment] 2023-06-27 17:48
Thanks for the super quick reply.

Ahhhh, I knew I had read something about this in the docs a while back! I just couldn't find it now.

Yes, your plan sounds amazing. :) I'll be looking forward to it. Thanks again for your hard work! Beartype is an amazing piece of technology and appreciated by everyone.

We're certainly having an excellent summer over here, though perhaps a bit hot at times. *Sweat drips.* I hope that you're also having a great summar in your cottage in the Canadian wilderness.
