### ISSUE TITLE
Claw and TYPE_CHECKING

### ISSUE THREAD

**Issue by tolomea** [beartype/beartype#259] opened 2023-07-22 08:34 UTC
I'm trying out claw on a project and I'm getting a lot of warnings like:

```
..\..\..\.venv\eligible310\lib\site-packages\beartype\_decor\decorcore.py:420
  C:\Users\Gordon\.venv\eligible310\lib\site-packages\beartype\_decor\decorcore.py:420: BeartypeClawDecorWarning: Generator factory method brianpost.email_category.EmailCategory.get_send_tasks() in file "C:\Users\Gordon\code\eligible\eligible\brianpost\email_category.py" line 277:
  generator factory method brianpost.email_category.EmailCategory.get_send_tasks() return PEP 563-postponed type hint 'Iterable[SendTask]' syntactically invalid (i.e., "name 'SendTask' is not defined") under:
```

In that file SendTask is imported inside a `if TYPE_CHECKING:` guard.

Is this warning expected? what should I do about it?

**Comment by gabrieldemarmiesse** [comment] 2023-07-22 10:47
By curiosity, why do you need to import it conditionnally? Usually, when I see `if TYPE_CHECKING:` that's a hint that some black magic is coming.

Note that you would have the same issue if you resolved the annotations of `get_send_tasks` yourself, it's not really an issue with beartype. The issue is more "how can I read the type hints of my function at runtime if I use `if TYPE_CHECKING:`?"

**Comment by tolomea** [comment] 2023-07-22 11:05
The usual answer, circular imports.

Database schemas are frequently circular. And so in Django you either end up with huge model files, circular referencing model files or both.

It's mostly fine Django has ways to express the links without importing the actual model classes and in the code that goes on the model classes you don't tend to need the actual model classes for the stuff you are manipulating as you are normally accessing it through relations... except for the type hints.

We don't have much, across 186,000 lines of code there are 6 instances of `if TYPE_CHECKING:`. That's mostly cause while the models reference circularly there is a reasonably well followed hierarchy to code. And type hinting in this project is very patchy.

**Comment by gabrieldemarmiesse** [comment] 2023-07-22 11:52
Indeed circular dependencies are quite hard to deal with. Since beartype inspect functions at import time, I don't think the delayed evaluation of annotations helps here...

**Comment by leycec** [comment] 2023-08-03 04:32
@tolomea and @gabrieldemarmiesse! My two new favouritest `beartype.claw` consumers combine their fearsome powers.

To help clarify this discussion, let us boldly rename `TYPE_CHECKING` to `I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER`. The original name `TYPE_CHECKING` is terse (which is good) but also dishonest and ambiguous (which is bad). The *new* name `I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER` is beyond verbose (which is actually good in this case, because nobody would *ever* use an attribute with a name like that in production code, which they arguably shouldn't, because production code should never ship lies) but also honest and unambiguous (which is also good). In short, `I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER` is what `TYPE_CHECKING` *should* have been named.

I don't know whether static type-checkers support type aliases in conjunction with `TYPE_CHECKING`, because I am lazy. But if they do, consider refactoring the six occurrences of suspicious code like this in @tolomea's codebase:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    # Insert shambolic lies, smelly filth, and QA degeneracy here.
    # Feels good, but it's actually bad.
    ...
```

...into even *more* suspicious code that is at least honest about what it's accomplishing like this:

```python
from typing import TYPE_CHECKING as I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER

if I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER:
    # Insert shambolic lies, smelly filth, and QA degeneracy here.
    # Feels good, but it's actually bad – but at least you're now
    # honest with yourself, your coworkers, and that sketchy Las Vegas
    # investment firm hoping to assimilate your tech startup for pennies
    # on the dollar about it. Two of those three things are good.
    #
    # If somebody starts yelling about this, redirect them to this issue.
    ...
```

Clearly, @beartype doesn't intersect with `I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER` very well. The whole point of @beartype is that you're *not* supposed to lie to @beartype; in return, @beartype tries as hard as it can to return that favour by not lying to *you*, either.

Thankfully, it looks like this issue is actually just about circular import dependencies:

> The usual answer, circular imports.

**Ah-ha!** Darkness, my old friend. Come to visit us again, have you? :face_exhaling: 

> Database schemas are frequently circular. And so in Django you either end up with huge model files, circular referencing model files or both.

`</nods_furiously>`

> It's mostly fine Django has ways to express the links without importing the actual model classes and in the code that goes on the model classes you don't tend to need the actual model classes for the stuff you are manipulating as you are normally accessing it through relations... **except for the type hints.**

`</nodding_continues>`

## PEP 484: What Isn't It Right About?

[PEP 484-compliant forward references](https://peps.python.org/pep-0484/#forward-references) are the way. Thankfully, @beartype has fully supported **absolute forward references** (i.e., type hints that are the fully-qualified names of model classes defined in other modules that live elsewhere in your sprawling codebase whose UML diagram increasingly resembles a Mandelbub render of a fractal Ouroboros snake eating its own tail) since, like, forever. They look like this:

```python
# In "yer_cool_package.yer_cool_submodule_A":
class MuhCoolModel(SomeWildAndCrazyDjangoModelThingy): ...
```

```python
# In "yer_cool_package.yer_cool_submodule_B":
from beartype import beartype

@beartype
def muh_cool_func(muh_cool_model: 'yer_cool_package.yer_cool_submodule_A.MuhCoolModel') -> None: ...
```

@beartype is absolutely fine with simple stringified type hints like `'yer_cool_package.yer_cool_submodule_A.MuhCoolModel'`. PEP 484 standardized that, so @beartype complies with that. Specifically, @beartype defers the resolution of the actual type underlying that forward reference until the last possible moment – which is to say, until the first time that the `yer_cool_package.yer_cool_submodule_B.muh_cool_func()` function is called. If the circular imports in your codebase are so incestuous that they can't tolerate even that, then @beartype can only mewl pathetically and blame the incoherent architecture of your app for falling down on its own sword. Seriously. Please investigate whether you can sanitize and streamline that madness before it erupts into a mud volcano. :volcano: 

@beartype does *not* attempt to resolve forward references at decoration time, as doing so would entirely defeat the real-world use case for forward references. Right? 

## Everything Else Is Unbelievably Bad

[PEP 563](https://peps.python.org/pep-0563/) (i.e., `from __future__ import annotations`) is *not* the way. @beartype's support for PEP 563 is spotty at best – and arguably broken at worst. That is obviously bad and a critical issue @beartype needs to work on. Generally speaking, it's currently best to avoid `from __future__ import annotations` if you intend to do *any* runtime type-checking whatsoever. This includes `beartype`, `typeguard`, Pydantic, and that inscrutable new kid on the block that almost certainly involves a shady AI doing shady things with your proprietary confidential information. <sup> :grimacing: </sup>

Likewise, `typing.I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER` is more obviously *not* the way – and that's *not* something @beartype can reasonably resolve, because `typing.I_AM_NOW_LYING_TO_YOU_STATIC_TYPE_CHECKER` shouldn't even exist in the first place. Nobody should be lying to anybody about anything. Right?

## This Has Been a Message of the @beartype Broadcasting Service

— *beep* —

Everybody, please let me know if @beartype can do anything better here... aside from better PEP 563 support, which *will* happen... just as soon as I've played every video game ever, this summer. These video games aren't gonna play themselves!

Until then, let's quietly close this and pretend I actually did something. :smiling_face_with_tear:

**Closed by leycec** 2023-08-03 04:32 UTC

**Comment by tolomea** [comment] 2023-08-03 08:40
So essentially the answer to:

> Is this warning expected? what should I do about it?

is "yes, use stringified type hints instead"

I can work with that.

Now I need to read up on annotations. We as a matter of course do all from futures we can, so we have annotations everywhere not cause we wanted some functionality but because it's the future. (likewise we run latest black with the preview flag)

**Comment by leycec** [comment] 2023-08-04 04:27
*...heh.* You just summarized my twenty-page rant with a single sentence. I'll take it. :laughing: 

> We as a matter of course do all from futures we can...

**Woah!** I've actually never heard of anyone doing that. That's a fascinating approach, though. In general, you're *absolutely* right; since most futures do represent Python's intended development path, enabling most futures bulwarks your codebase against future Python releases. In practice, however, there are *always* exceptions. Nothing is unconditionally good – not even the future. `from __futures__ import annotations` is that exception.

Almost everything that `from __futures__ import annotations` does is good. But one specific thing that `from __futures__ import annotations` is so bad that it self-destructs the whole thing. What is that bad thing? PEP 563 – the Python standard so catastrophic it delayed the release of Python 3.10 by several months, broke *all* runtime type-checkers and downstream packages leveraging runtime type-checkers (including Pydantic and FastAPI), and ignited a vociferous controversy throughout the Python community which continues to this day. Because PEP 563 is demonstrably bad, `from __futures__ import annotations` is demonstrably bad, too. Indeed, the [official release notes for Python 3.11 explicitly state](https://docs.python.org/3/whatsnew/3.11.html#pep-563-may-not-be-the-future):

> ## PEP 563 may not be the future

> [PEP 563](https://peps.python.org/pep-0563/) Postponed Evaluation of Annotations (the `from __future__ import annotations` [future statement](https://docs.python.org/3/reference/simple_stmts.html#future)) that was originally planned for release in Python 3.10 **has been put on hold indefinitely.** See [this message from the Steering Council](https://mail.python.org/archives/list/python-dev@python.org/message/VIZEBX5EYMSYIJNDBF6DMUMZOCWHARSO/) for more information.

My personal expectation is that some future Python release will quietly deprecate `from __futures__ import annotations`. You should probably *never* enable `from __futures__ import annotations` in production code unless you absolutely must, because that future isn't actually the future; it's just an optional feature that didn't behave as intended and is likely to go away at some point. Your mileage may vary, of course. This has been a message of the Beartype Broadcasting Corporation (BBC).

**Comment by eli-schwartz** [comment] 2023-11-01 00:38
I'm not entirely sure I understand the problem here -- the concept behind `from __future__ import annotations` is essentially "pretend as if every single annotation, bar none, was quoted, but without actually quoting them". Why is it bad to use this...

... but perfectly fine to manually quote them?

**Comment by leycec** [comment] 2023-11-01 05:29
*...heh.* I have been summoned from ~~the dead~~ playing video games. The problem is that [what you want to do is **officially deprecated** under Python ≥ 3.13](https://github.com/beartype/beartype/discussions/299), which is pretty much as bad as it gets. The Ghost of Python Past cries out in lamentations! :ghost:

**Comment by eli-schwartz** [comment] 2023-11-01 11:12
You didn't say it was uncool to use it -- you said that beartype mishandles it.

If it's deprecated and not the future anymore then an argument can be made that it's not worth future investments, and an argument can also be made that it is uncool to use it and by doing so make a statement that it is the future and you are using it. But its deprecation in 3.13 does not actually cause python <=3.12 to suddenly change language semantics and behave differently without any code changes to python, than it behaved before the news was announced.

So that's really the root of my question here: given the technical semantics of what the import actually does -- why does beartype have a harder time parsing stringified annotations that were stringified by the bytecode compiler, vs. stringified annotations that were stringified by a text editor inserting quotation chars?

I'm simply curious -- no need to answer if the topic is too ugly. ;)
