### ISSUE TITLE
Classes not supported by beartypes yet?

### ISSUE THREAD

**Issue by mxlei01** [beartype/beartype#89] opened 2022-01-28 10:49 UTC
I tried to use beartype + dataclass as per the example, but I'm getting an exception:

```
from beartype import beartype
from dataclasses import dataclass

@beartype
@dataclass
class MyDataclass:
    nothing: str

beartype.roar.BeartypeDecorWrappeeException: <class '__main__.MyDataclass'> unsupported, as classes currently unsupported by @beartype.
```

I'm currently on Python 3.9, and Beartype 0.9.1, is this something not supported in Beartype yet?

**Comment by leycec** [comment] 2022-01-29 07:24
Max, I have good news and I have bad news.

The good news is that our upcoming `beartype 0.10.0` release officially supports dataclasses according to [our scary *Features* matrix that nearly makes my browser blow up](https://github.com/beartype/beartype#Features)! The bad news is that `beartype 0.10.0` has yet to be released. `</gulp>`

While we're all waiting for me to release `beartype 0.10.0` already, consider [this super-clever four-liner by Swedish typing mastermind @antonagestam](https://github.com/beartype/beartype/issues/56#issuecomment-938713933):

``` python
from beartype import beartype
from dataclasses import is_dataclass
from typing import TypeVar

T = TypeVar("T")

def beartype_dataclass(cls: type[T]) -> type[T]:
    assert is_dataclass(cls)
    cls.__init__ = beartype(cls.__init__)  # type: ignore[assignment]
    return cls
```

Decorate dataclasses with that placeholder `@beartype_dataclass` decorator instead: e.g.,

``` python
@beartype_dataclass
@dataclass
class MyDataclass:
    nothing: str
```

Of course, this is all my fault. Apologies for the confusion – and I promise we'll release `beartype 0.10.0` before I collapse under the stress live in a slo-motion Twitch stream. Anyone else finding it hard to breath in here? No? That just me? :face_exhaling:

**Comment by leycec** [comment] 2022-01-29 07:24
*marked as duplicate of #56*

**Closed by leycec** 2022-01-29 07:24 UTC
