### ISSUE TITLE
Dict contents are never checked with die_if_unbearable

### ISSUE THREAD

**Issue by uriyasama** [beartype/beartype#313] opened 2023-12-05 15:48 UTC
Very easy bug to reproduce:

```
from typing import Dict

from beartype.door import die_if_unbearable

obj_type = Dict[str, int]

die_if_unbearable(
    {"x": "y"},
    Dict[str, int],
)
```

While in Sequence likes, the inside of a compound object is checked according to O1 strategy, it seems like dictionaries insides are never checked. From what I tried, the only way to fail this typecheck is if the value isn't a dict in the first place.

**Comment by leycec** [comment] 2023-12-06 06:31
**Indeed.** It's all true, @uriyasama! 申し訳ございません。 :bow: 

Allow me to now explicate in English, because my Japanese is truly trash. Beartype currently only [deeply type-checks a handful of core container types like `list` and `tuple`](https://beartype.readthedocs.io/en/latest/pep). Specifically:

* For [each type with **full support** in this table](https://beartype.readthedocs.io/en/latest/pep), @beartype deeply type-checks that type (i.e., type-checks both the type and items of that type).
* For [each type with only **partial support** in this table](https://beartype.readthedocs.io/en/latest/pep), @beartype only shallowly type-checks that type (i.e., type-checks *only* the type).

Obviously, this is ~~horrible~~ "non-ideal." Our focus in 2023 has been shallowly type-checking literally everything so that you can throw @beartype at any class or callable *without* @beartype raising an exception. Hurrah! We're basically there. This means [our focus in 2024 will be deeply type-checking literally everything](https://github.com/beartype/beartype/discussions/292).

Until then, I have only these apologies to give. Since this issue is technically a duplicate of long-standing feature request #53, let's quietly close this for my own personal sanity. Yet again, I bow. :bow:

**Closed by leycec** 2023-12-06 06:31 UTC
