### ISSUE TITLE
[BUG] False Positive when using Iterable

### ISSUE THREAD

**Issue by ShaneHeldsinger** [beartype/beartype#186] opened 2022-11-15 10:10 UTC
When running the code below there is **no** error thrown even though I would expect an error.  

```
from beartype import beartype
from beartype.typing import Iterable

@beartype
def test(numbers: Iterable[int] ) -> None:
    print(numbers)

test("test")
test([True, False])
```

I have noticed when using Iterable with any type, (eg. Iterable[bool], Iterable[str], Interable[int], etc.) it ignores the type (bool, str, int) and only throws an error if the argument is not Iterable. Is this intentional?

**Comment by leycec** [comment] 2022-11-15 20:08
**Gah!** Horrifyingly, it's all true; @beartype has yet to support deep type-checking for as many categories of type hints as we would like. This includes `Iterable[...]`, which is *kinda* non-trivial to safely deeply type-check. The existence of so-called one-shot iterables like generators means that @beartype needs to be cautious about how, what, where, and when exactly it deeply type-checks iterables. There be steaming dragons there. :cloud: :dragon_face: 

The good news is that our upcoming `beartype 0.13.0` release cycle will be focussed on deep type-checking! We'll be extending deep type-checking support to core container types like dictionaries, sets, and (...*hopefully*) `Iterable[...]`. For now, please see:

* Our [**features matrix**](https://github.com/beartype/beartype#features) for an exhaustive breakdown of the type hints @beartype shallowly and deeply type-checks.
* This [**existing issue on deep type-checking support**](https://github.com/beartype/beartype/issues/53), where we're tracking improvements to deep type-checking in @beartype.

## But Wait... There's More

Thankfully, there's something you can do about this until we do this for you. Using the obscene power of **[beartype validators](https://github.com/beartype/beartype#beartype-validators)**, you can have your QA cake and eat it too:

```python
# Import the requisite machinery.
from beartype import beartype
from beartype.vale import Is
from beartype.typing import Iterable
from typing import Annotated   # <--------------- if Python ≥ 3.9.0
#from typing_extensions import Annotated   # <--- if Python < 3.9.0

# Type hint matching an iterable of integers in O(1) time.
IterableInt = Annotated[Iterable[int], Is[lambda iterable:
    iterable and isinstance(next(iter(iterable)), int)]]

# Annotate with "IterableInt" rather than "Iterable[int]".
# Yes, we should fix this for you as soon as human life permits.
@beartype
def test(numbers: IterableInt) -> None:
    print(numbers)
```

The proof is in the IPython REPL:

```python
# This works, because booleans are technically integers in Python.
# Look. Don't ask. We blame Guido.
>>> test([True, False])
[True, False]
# This fails as expected. Hallelujah!
>>> test("test")
beartype.roar.BeartypeCallHintParamViolation: @beartyped __main__.test() parameter
numbers='test' violates type hint typing.Annotated[collections.abc.Iterable[int],
Is[lambda iterable: iterable and isinstance(next(iter(iterable)), int)]], as str
'test' violates validator Is[lambda iterable: iterable and
isinstance(next(iter(iterable)), int)]:
    False == Is[lambda iterable: iterable and isinstance(next(iter(iterable)), int)].
```

:muscle: 

Since this is a duplicate of issue #53, let's quietly close this and continue the discussion over there. `beartype 0.13.0` should resolve this for you sometime early next year. Until then, thanks for all the interest! You rock, @ShaneHeldsinger.

**Closed by leycec** 2022-11-15 20:08 UTC
